### ISSUE TITLE
Quick navigation through document structural elements

### ISSUE THREAD

**Issue by jrbowden** [daisy/ebraille#1]
As a braille display user, I want to use the structural elements of a document to navigate more quickly through the document, similar to what I can already do with a screen reader when reading web pages, Word documents or well structured PDF documents.

*Detail:*
Screen readers on computers and smart phones offer a variety of "quick navigation" functions which allow me to jump to various structural elements in the document I am reading. Structural elements include headings, paragraphs and many other types of elements.

I'd like to navigate in a similar way when reading a braille file on my braille display, for example press a button/buttons to jump straight to the next or previous heading.

Currently, braille files do not include structural elements, so I can only search on text.

*Proposal:*
The braille file should include structure, similar to other rich format documents.
At a minimum, navigable  structural elements would include:
- Headings
- Paragraphs
- Tables

Many more types can be added - full list to be discussed.

**Comment by franciscoONCE** [comment]
The structure required here can be mapped with the structure provided by an EPUB/DAISY file. There are already out there conversion tools that take the text out of an EPUB file and turns it into braille - the next step would be to "export" the original navigability elements of the EPUB file to the resulting braille file.

**Comment by jrbowden** [comment]
Yes, there is a rich selection of document elements available in HTML or EPUB; we will need to consider a defined set, and also if there any new elements, specific to braille.

**Comment by mattgarrish** [comment]
The document structuring aspects are well handled by the various publishing formats, but there's also a question here whether quick navigation equates to things like a table of contents, page list, and landmarks.

All the formats allow for these but in different forms.

- EPUB, DTBook, and pub manifest all have a programmatically determinable tables of contents. HTML doesn't, unless it's a single page document (the doc-toc role could be used in that case).
- EPUB, DTBook and pub manifest also have programmatically determinable page lists.
- EPUB, HTML, and pub manifest also have ARIA landmarks, while EPUB (landmarks nav) and DTBook (guide) also have their own publication landmarks.

**Comment by bertfrees** [comment]
I can also see the possibility of extending PEF (the braille file format for transcribed, formatted and paginated content) with an "anchor" feature (like the HTML &lt;a&gt; tag), so that it could be accompanied by some navigation document that would reference specific locations in the PEF.

**Comment by wfree-aph** [comment]
By using xHTML and the EPUB packaging format, the features discussed here are possible. It will depend on authors properly using markup and reading systems taking advantage of that markup but the spec itself does not prevent these features and specifically mentions them in the [Tagging Best Practices](https://github.com/daisy/ebraille/blob/main/best-practices/tagging/index.html) document. Closing this issue as resolved.
