### ISSUE TITLE
Hide text based on the user's preferences

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#10]
As a dynamic braille display user, I want to hide information that isn't necessarily relevant to my current reading experience such as running heads and print and braille page numbers.

*Detail:*
Running heads are the headings that appear at the top of printed and embossed pages. Their purpose seems to be related to the physical nature of the material and to ensure that the contents of one collected set of pages do not get mixed up with the contents of another set. In a digital reading medium, they become much less useful and so could be removed. The reader could call up the information using a location query depending on what was available in the software they were using.

Print and braille page numbers are somewhat more useful than running heads even in a digital reading medium but they still take up a lot of space on the braille line and aren't necessarily always necessary to know, The reading software could similarly provide a command that makes a location query and displays the reader's current print and braille page number. Even hidden, the user could still navigate using this information if they so required.

*Proposal:*
Running heads and print and braille page numbers should be marked up so that reading software can, based on the user's preferences, hide and recall them as needed. You'd want to allow for the hiding of each separately, so that a user could choose to keep, for example, the print page numbers but hide the running head and braille page numbers.

**Comment by franciscoONCE** [comment]
I see this feature extremely useful to hide footnotes, for instance, or other elements in the text that are only required in certain cases. This is something that is already present in EPUB/DAISY books - hence, this could be mapped with the existing EPUB standard (like most of the structural and navigational elements required for braille books, for that matter). The running heads and page numbers are part of the structure of an embossed braille page, but shouldn't necessarily be in the "source" e-braille file we are devising here - these should appear only in the "printing file", in the output file that we should be able to create from it when embossing is required.

**Comment by avneeshsingh** [comment]
Indeed these structural elements should be marked well so that reading device can decide to show or hide them.
It looks as a high priority use case. What do we think?

**Comment by wfreeman-aph** [comment]
Meeting: proposed to change title to "Hiding header/footers and page numbers". Also, changing to something that makes it clear we're discussing adding semantics so that they can be hidden by the reading system later.

**Comment by mattgarrish** [comment]
DPUB ARIA has doc-pagenumber and whenever we get the 1.1 update out it might have doc-pageheader and doc-pagefooter (these are new so we still have to show use of them before they'll become official). That would allow these to be expressed in all the HTML-based formats.

As DTBook doesn't incorporate the role attribute, I think it might be limited to page numbers.

**Comment by bertfrees** [comment]
Running headers/footers and braille page numbers could also exist only in the style. E.g. CSS can be used to generate content in page margins. A style sheet could easily hide page margins on certain media (through CSS media queries), and the device itself could also disable them.

**Comment by wfree-aph** [comment]
The markup necessary for this feature is included in xHTML and mentioned in the [Tagging Best Practices](https://github.com/daisy/ebraille/blob/main/best-practices/tagging/index.html) document. Other than that, this is a reading system feature that is otherwise outside of our control and so we can close it as resolved.
