### ISSUE TITLE
Braille Codes

### ISSUE THREAD

**Issue by GouldenJen** [daisy/ebraille#104]
GitHub tickets: #41 and #20    
Requested Metadata: Identifies any braille code(s) used in the file.
NLS Dublin Core Element:dc:Format
Notes from GitHub tickets: Need a controlled vocabulary
Notes from Metadata team: NLS repeats this element as many times as needed if multiple braille codes are present in the BRF. Is there an existing source of codes? World Blind Union?
Jen: See World Braille Usage for information on braille codes other than English: https://www.perkins.org/resource/world-braille-usage/

**Comment by skntkacm** [comment]
I am not sure, how this could be adopted within ebrf, but... Concerning the other braille codes than ehglish, there is a project Liblouis, which is widely used by the most screen readers for interpreting braille patterns. Liblouis tables are updated quite often as they are integrated part of many OS platforms. 
https://github.com/liblouis/liblouis

**Comment by bertfrees** [comment]
Liblouis has indeed done an attempt to categorize braille tables and tag them with metadata. But important to note is that:

- The metadata may in some cases be inaccurate, especially for the metadata that has not been verified by natives.
- Liblouis does not have tables for all variants of every braille code, and it is not impossible that there are languages for which multiple braille codes exists, of which Liblouis has only implemented some.

**Comment by wfree-aph** [comment]
Braille code is required in the [first draft of the specification](https://github.com/daisy/ebraille/blob/main/index.html), under section 5.2. Closing this issue as completed.

**Comment by bertfrees** [comment]
As a developer of software for automatic conversion to eBraille files, I am unsure what the required format is for the braille code and braille grade metadata. The spec doesn't go into this. Should the software ask the user to provide this required information?

I apologize for missing some of the discussions on metadata, perhaps this has been discussed.

**Comment by wfree-aph** [comment]
@bertfrees, you're correct that we don't yet have a standardized language for braille codes and grades. I will make an issue for that. It's not easy and I have put it off and need to address it. At the end of the day though, it will just be strings and so I don't think we need it figured out before releasing the first spec draft.
