### ISSUE TITLE
Tactile Graphic File Type(s)

### ISSUE THREAD

**Issue by GouldenJen** [daisy/ebraille#108]
GitHub ticket: #41
Requested metadata: Tactile graphic file type(s)
NLS Dublin Core Element: N/A 
Alternative dc or schema.org: refines x-metadata brl:tactileGraphics OR
dc:Description? 
Notes from GitHub ticket: Support for different tactile graphic file types could vary among different hardware 
Notes from metadata team: What will reading systems need for this? Can refines repeat for multiple file types?

**Comment by wfree-aph** [comment]
The metadata term graphicType is in the [first draft of the specification](https://github.com/daisy/ebraille/blob/main/index.html), section A.5.2. Closing this issue as completed.
