### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by GouldenJen** [daisy/ebraille#109]
GitHub ticket: #41
Requested metadata: language(s)
NLS Dublin Core Element: dc:Language
Notes from GitHub ticket: NLS uses RFC 1766 and ISO 639-1 compliant language code and optional country code sub-tag.

**Comment by wfree-aph** [comment]
Language is required in the [first draft of the specification](https://github.com/daisy/ebraille/blob/main/index.html) and is found under section 5.2. Closing this issue as resolved.
