### ISSUE TITLE
Rights metadata

### ISSUE THREAD

**Issue by nicolegaines** [daisy/ebraille#113]
Many publishers like to include a Rights statement with their copyrighted materials. This could be an optional element/field for whatever text a publisher or authorized entity would like to supply for the eBraille file.

**Comment by wfreeman-aph** [comment]
It was agreed at the 11/14/24 meeting to keep this as optional. The idea here would be that a library or producer could make the licensing rights of the work clear. For example this metadata label could be used to show that the file has a Creative Commons license or a restricted license, etc.
