### ISSUE TITLE
Metadata: Date of original eBraille Production

### ISSUE THREAD

**Issue by nicolegaines** [daisy/ebraille#114]
NLS uses:  x-metadata brl:producedDate for this metadata. Is this something that should be required or optional for eBraille?

NLS uses this element for the original date and the metadata is retained in all subsequent versions. A separate element is used   for revision date. For simplicity, producedDate could be used to refer to the   current eBraille file production date without concern for any prior versions.   There is not an existing use case for retaining historical creation date   metadata but this can be open for discussion.

**Comment by wfree-aph** [comment]
This need is reflected in the published spec with a11y:created. If something else is needed here, we can reopen this issue or open a new one.
