### ISSUE TITLE
Metadata: Revision Date

### ISSUE THREAD

**Issue by nicolegaines** [daisy/ebraille#115]
Is there a rationale for including an optional or required metadata element for Revision Date of the eBraille file? This is metadata that NLS captures using this element:

x-metadata brl:revisionDate

NLS captures original date, revision date, and version number in separate elements.

**Comment by wfree-aph** [comment]
The main request of this issue is represented in the spec with the value dcterms:modified. If more is needed, such as original date or version number, those should be put in a new issue.
