### ISSUE TITLE
Metadata: Grade Level

### ISSUE THREAD

**Issue by nicolegaines** [daisy/ebraille#117]
For instructional materials, Grade Level is a useful data point for catalogers and searchers. This would need to support a range of controlled vocabularies depending on the country. Dublin Core and schema.org use EducationalAudience for this metadata:
https://www.dublincore.org/specifications/lrmi/lrmi_terms/2022-06-14/#EducationalAudience

**Comment by wfreeman-aph** [comment]
It was decided at the 11/14/24 meeting to keep this metadata item as optional. While we won't be able to standardize its usage, like the identifiers, it could be managed at the organizational level and be very useful in that regard.

**Comment by egli** [comment]
I would suggest that if we add this as metadata then it should be named _EducationalAudience_
