### ISSUE TITLE
Metadata: Tactile Graphics Present (Yes/No)

### ISSUE THREAD

**Issue by nicolegaines** [daisy/ebraille#118]
This element could be required to indicate whether or not any graphics are present in the eBraille file. This may be particularly useful when the eBraille is generated by an automated conversion and no graphics are present. NLS uses this element:
x-metadata brl:tactileGraphics 
Additional details could be provided under dc:Description.

**Comment by wfreeman-aph** [comment]
Like I mentioned in [ticket #121 ](https://github.com/daisy/ebraille/issues/121#issuecomment-1806292967), I think we need more than a yes/no here. For graphics you could have two seemingly identical graphics but one uses different CMYK values for the color black and suddenly the graphic will not emboss properly. I don't know that we should try to get so specific (and we certainly should avoid it for MVP) but we should at least include file type, whether graphics include braille, and, maybe, eventually have some means for users to indicate what kind of hardware will best produce the graphic. Some may be preferable in a dynamic medium, while others will require a higher DPI, or need advanced and detailed textures to make sense. None of this metadata would prevent a user or hardware from attempting to display something but it would at least give developers for options.

**Comment by franciscoONCE** [comment]
We have two brl: tags for this right now, brl:tactileGraphics and brl:graphicType. If we're following Daisy metadata whenever possible, we might consider changing them into a brl:multimediaContent tag only. If emptly, no images are included in the document; otherwise, we might state here which types of images are included.

**Comment by franciscoONCE** [comment]
Thanks, Nicole. I agree with your view on this issue. Actually, it was more of a question than an answer to the problem, so I'm glad you clarified this for me. I agree that multimedia in Daisy refers to more than images (though I wonder if this new braille format would also support including audio and/or video as examples in educational materials...) and that it may arise some confusion. 

I'd be happy with two metadata elements for this as you mentioned, though in that case I'd try to unify the names a little so the correlation between them is clearer. How about something like brl:Graphics and brl:graphicsType? The second element may explain if they are tactile or just images with a description and the specific extension of the graphics. The problem with the current brl:tactileGraphics is that it refers to a very specific type. Looking forward to more thoughts about this.

**Comment by mattgarrish** [comment]
If this metadata is primarily for reading systems, you might want to use the `properties` attribute on manifest items to be more specific. For example, we could define a new "tactileGraphic" property:

`<item media-type="image/jpeg" href="images/image01.jpg" properties="tactileGraphic"/>`

A reading system can then determine exactly which resources are tactile graphics and what format each is in.

**Comment by nicolegaines** [comment]
Hi, Francisco. I like the suggested tags, but I have a question about using the second tag to indicate not only the file extension but whether the image is a tactile graphic or not. It raises an important point, which is that we may not necessarily know from the image file extensions whether the images are tactile graphics, or if they are "regular" images retained from the source file format.

My understanding from the MVP on the wiki is that, technically, eBraille does not support the inclusion of "regular" images. I have been actually been concerned all along that there will be folks who do automated transformations from other file formats into eBraille, but make no changes to the source graphics, and that this will result in eBraille graphics that can't be successfully used in digital or embossed format.

Although there is not a way to make an eBraille file fail validation if the image files are not tactile graphics, I think that the files would in fact not be "valid" eBraille if the tags intended for tactile graphics are used to supply original print-based image files.

Nicole

________________________________

**Comment by GeorgeKerscher** [comment]
Hi,
 
I would think that a student would want to be able to submit the original image to an AI service for description. Reading Systems may also provide this as a feature to make it even easier. Also, being able to show the image to others would be nice. For these reasons, I think we should allow for the original images to be included.
 
Best
George

**Comment by clapierre** [comment]
Hello all,

Regarding embossing images, I would think there may be services that could potentially take an image and create a braille representation of that image for embossing if this doesn't already exist, and as George points out to be able to get an AI description of that image could also be a feature for some reading systems to provide.

So, I agree knowing if this image is preformatted braille or a generic visual image would be important to know.


Thanks

Charles

EOM



________________________________

**Comment by nicolegaines** [comment]
Hi, George. I'm intrigued by this idea but am unclear about how this is going to work in practice. I may just not be thinking ambitiously enough in terms of what we expect the reading software is going to be able to do. I do think AI is going to revolutionize accessibility in the near future and so you may be on the mark in terms of this use case.

But I think that if we are going to consider source file images appropriate for inclusion in eBraille files, then it's going to be essential that we have required tagging to mark these in some way at the image level as "not intended for digital display / not intended for embossing." It's going to be important that braille devices and embossers be able to identify them as not usable for these purposes and automatically skip them.

This will be particularly essential if we are saying that in the same file you can have tactile graphics and original source images mixed in together.

Again, my understanding from early on in the eBraille spec work was that image files included in eBraille should be tactile graphics or not present.

I'm not at all averse to reconsidering that, but as far as I know, the implications of this change on users, readers, embossers, and production software have not yet been explored by the group. I would recommend that the group consider this proposed change from various angles before making a decision.

Thanks.

Nicole


________________________________

**Comment by wfree-aph** [comment]
This metadata term is present in the [first draft of the specification](https://github.com/daisy/ebraille/blob/main/index.html). Closing this as completed.
