### ISSUE TITLE
Automatic conversion from excellent source files to E-Braille

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/ebraille#12]
As a distributer of accessible file formats, we want to support delivery of content in the E-Braille file format.

Problem statement:  Libraries and organizations serving persons with disabilities want to support a wide range of formats used by their customers and patrons. To do this, conversion routines from one file format to another should be supported. The three most widely used rich file formats  are DAISY 3 and 2.2, EPUB 3, and for some applications HTML. We also expect that Journal Article Tag Suite (JATS) will become an important source for scholarly journals.

These formats support rich semantics, such as: multiple heading levels, page numbers, tables, ordered lists, bulleted lists, images, MathML, and more.
 
For our purposes,  one thought to consider is  to treat the source digital version as the primary version. In other words, if a print version  also exists, we do not attempt to match the formatting  from the print, but use the semantics from the digital version as the primary source. In this way, the semantics of the digital source can be mapped for automatic conversion in the E-Braille format. The automatic conversion will ensure that Hundreds of thousands or even millions of titles  become available in the E-Braille format.

**Comment by franciscoONCE** [comment]
Excellent point, George! That is also my vision - a source file suitable for e-reading, with all the structural elments required, and an output file for printing following the guidelines of the producer/user. Could the source file be an EPUB/DAISY file, so that we can export all that wealth of structural and navigability features to the e-braille new file?

**Comment by clapierre** [comment]
This will be critical for Bookshare to offer over 1 million books in our collection to Ebraille.

**Comment by mattgarrish** [comment]
As we settled on an EPUB-compatible file set and OCF packaging for ebraille, I'm going to close this issue.
