### ISSUE TITLE
Metadata: ISBN

### ISSUE THREAD

**Issue by shepazu** [daisy/ebraille#120]
If a document has a registered ISBN (International Standard Book Number), this should be captured in the metadata.

It was initially suggested this might be in a `dc:Source` entry. 

DCMI recommends that this should be in a `dcterms:isPartOf` entry, and the [ISBN should be encoded in values of DC properties as value URIs](https://www.dublincore.org/specifications/dublin-core/dc-citation-guidelines/#52-identifiers). This would be encoded in the form `urn:ISBN:`. For example, `urn:ISBN:8884530431`.

## References:
- See #111 for related discussion of unique identifiers
- #27
- #41

**Comment by wfree-aph** [comment]
This need is reflected in the spec using dc:identifier. If more is needed here, this issue can be reopened or a new issue can be added.
