### ISSUE TITLE
Metadata: Copyright and/or Publication Date

### ISSUE THREAD

**Issue by shepazu** [daisy/ebraille#124]
- Requested metadata: 
  - Copyright date
  - Publication date
- NLS Dublin Core Element:
  - `date.dateCopyrighted`
  - `date.Issued`
- Notes from GitHub ticket: Copyright required, if applicable. Publication date optional but required if no copyright date

## References:
- #27

**Comment by wfree-aph** [comment]
Closing this issue in favor of a more specific issue that reflects the remaining need, which is #263.
