### ISSUE TITLE
Metadata: Producer Name (Human)

### ISSUE THREAD

**Issue by shepazu** [daisy/ebraille#125]
- Requested metadata: Producer name
- NLS Element: `x-metadata brl:producer`
- Notes from GitHub ticket: 
  - May also include location. Need to know if it’s human-generated or automated. If automated, what software was used to create the file.
  - NLS uses for producer name only.

## References:
- See #126 for software producer name
- #21

**Comment by wfreeman-aph** [comment]
Unlike the software metadata item, this information could be very useful and is probably good to keep. I also think it could help the quality of transcription as agencies and individuals would know how searchable their mistakes would be. I think we could cut this one if we had to but I would want to keep it much more than the software one.

**Comment by mattgarrish** [comment]
I've seen `dc:contributor` used along these lines in epub for listing the internal production people who helped in creating the digital version of a book. It can be paired with a [MARC relators code](https://id.loc.gov/vocabulary/relators.html) to indicate the specific role the person played.

**Comment by wfreeman-aph** [comment]
It was agreed at the November 14th to keep this as optional. Like the other optional criteria so far mentioned, it will be difficult to standardize but keeping it will still be useful at the organizational level.
