### ISSUE TITLE
Metadata: Producer Name (Software)

### ISSUE THREAD

**Issue by shepazu** [daisy/ebraille#126]
- Requested metadata: Software used to generate file
- NLS BOPF Element: `nls:generator`
- Notes from GitHub ticket: refines `brl:producer`? (This seems to have been criticized.)

## References:
- See #125 for human producer name
- #21

**Comment by wfreeman-aph** [comment]
This to me seems nice to have for completeness sake but I do think we could run the risk of asking for too much metadata. The data nerd in me loves this idea as you could learn what issues are specific to certain programs and the developers of those programs could fix them more easily but if we had to cut something to keep things simple, this is one I would cut.

**Comment by wfreeman-aph** [comment]
Another optional metadata item from November 14th meeting. We can recommend how to refer to the major producers in our recommendations document but there will be a limit to how much we can control this vocabulary as there will likely be changes in this field that we can't keep up with.
