### ISSUE TITLE
Metadata: Subject

### ISSUE THREAD

**Issue by shepazu** [daisy/ebraille#130]
- Requested metadata: Subject
- NLS Element: `dc:Subject`
- Notes from Excel file: Need to determine controlled vocabulary.

**Comment by wfreeman-aph** [comment]
At the 11/14/23 meeting it was agreed to keep this metadata label as optional. Like other optional labels, it will be difficult to control the vocabulary used but it could be managed at the organizational level and be very useful. One use case that was mentioned was that reading systems could, with some degree of success and usefulness, organize one's personal library by subject.
