### ISSUE TITLE
Hide text depending on user preferences

### ISSUE THREAD

**Issue by jrbowden** [daisy/ebraille#14]
Related to #10, this could be carried a lot further. For example, dynamically hiding or showing paragraphs of text, right through to hiding particular types of symbols, such as bold or italic signs.
This would need careful thought and would be a "nice-to-have" rather than essential feature.

As a braille user, new to braille, I can't understand all these extra dots around the words. I want to hide all the extra stuff so I can just read the actual text.

**Comment by avneeshsingh** [comment]
looking from content point of view, I think that it boils down to having proper mark-up for the elements listed by @jrbowden so that reading device can make a decision to hide some dots for making reading more fluent.

**Comment by wfree-aph** [comment]
Similar to #10, I believe this issue can be closed as resolved. It will be dependent on reading systems and authors to make the most use of the markup available in this specification.
