### ISSUE TITLE
Request to review and comment on Metadata: Simple List

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#141]
[Metadata: Simple List](https://github.com/daisy/ebraille/wiki/Metadata:-Simple-List) is an attempt to organize our metadata needs in a simple way, so just some headings and some lists. At the top are the required elements, then the optional and both of those are then organized by what standard they use, if any. Then there are items we agreed to not include and I also included duplicates in an attempt to ensure that I covered everything.

Please review that wiki and comment on this issue with any changes you would like to see. It would be helpful if, like the Tagging Best Practices document, that you state exactly what you would like to see change, how it should change, and why. If something is missing, please say where you think it should go in the hierarchy and, if possible, reference what standard we could use for it. Also, please feel free to make new issues for major changes or additions.

Appreciate any help! This wiki will be the basis for a Metadata Best Practices document but the thinking was that by keeping it simple for discussion, we might have an easier time sorting through what we have versus what we need. We can revise this plan if we find it is not suitable.

**Comment by jrbowden** [comment]
Dublin Core also has
dc: title: I was surprised not to read this in the Wiki. There's also the title tag, looking at DAISY books, they seem to have both title and dc:title.

I think the title, author and ISBN are the highest priority, though I am not a metadata expert.

DC: Date: should this be preferred over brl:producedDate?

Note also that there's the organisation name that produced the item, not necessarily the human name of the producer; the software used might in DAISY be called the "Generator" (see "ncc:generator").

**Comment by wfree-aph** [comment]
Thanks everyone for commenting on this wiki and helping to finalize the metadata terms for the first draft of the specification. I am going to close this issue now.
