### ISSUE TITLE
Do not use cryptic class names

### ISSUE THREAD

**Issue by egli** [daisy/ebraille#145]
The common set of class names that is used to tag ebraille should include names that at least somewhat indicate their meaning.

In particular the class name `tn` is way to cryptic and should probably be replaced with something that relates what is used for, such as (why not) `transcriber-note`, or even `brl-transcriber-note` (see #144)

**Comment by jrbowden** [comment]
Related to this is of course that all reserved class names should be fully documented.

On the subject of names, note that HTML does use cryptic names, such as p, tr, hr, li, to name a few. However, I do agree that our names should be recognisable to those who need them. An added complication is that not all braille codes have all the concepts needed for eBraille.
