### ISSUE TITLE
Invalid use of the class attribute

### ISSUE THREAD

**Issue by egli** [daisy/ebraille#146]
The eBraille Tagging Best Practices document contains multiple examples where the class attribute is used multiple times on the same element, i.e. 

``` html
<div class="box" class="blue">
   <p>⠠⠎⠑⠑ ⠁⠇⠎⠕ ⠠⠉⠓⠁⠏⠞⠑⠗ ⠼⠃⠑</p>
</div>
```

As far as I know this is not valid and the WHATWG HTML specification seems to confirm that [section 12.2.4.33 "Attribute name state"](https://html.spec.whatwg.org/#attribute-name-state):

> When the user agent leaves the attribute name state (and before emitting the tag token, if appropriate), the complete attribute's name must be compared to the other attributes on the same token; **if there is already an attribute on the token with the exact same name, then this is a parse error and the new attribute must be dropped**, along with the value that gets associated with it (if any).

So I think these examples should be rewritten as follows:

``` html
<div class="box blue">
   <p>⠠⠎⠑⠑ ⠁⠇⠎⠕ ⠠⠉⠓⠁⠏⠞⠑⠗ ⠼⠃⠑</p>
</div>
```

If you like I can create a PR

**Comment by wfreeman-aph** [comment]
Thanks for catching this error. If there are no objections, I will go through and fix this problem, make a pull request, and then we can resolve this ticket.
