### ISSUE TITLE
Change in Problem Statement

### ISSUE THREAD

**Issue by ManfredMuchenberger** [daisy/ebraille#15]
When reading the whole Problem Statement again (which in my opinion is a very good description of the problem) I stumbled across something I think is worth changing.
In the last paragraph of the chapter "Issue" just before the chapter "Scale" begins.
https://daisy.org/activities/projects/ebraille/problem-statement/

It is clear that content and presentation must be separated. But to my opinion at least part of the formatting should be adapted by the reading system according to the device that is being used for reading. So it will not completely be "retained" from the braille file. Also I wouldn't call "braille translation" simple and it can't be completely error-free automated by reading software. At least not for German contracted Braille. This "error free braille translation" will be the most important reason for us to introduce e-braille.
My suggestion is to just delete this paragraph in the Problem Statement, as the file sharing is already sufficiently described in the paragraph above this.

**Comment by wfree-aph** [comment]
Unfortunately we were not able to remove this paragraph. I don't feel it is appropriate to change the Problem Statement at this time but I do feel the issues you raised in your ticket @ManfredMuchenberger are addressed in the 
[first draft of the specification](https://github.com/daisy/ebraille/blob/main/index.html). I will close as not completed.

**Comment by ManfredMuchenberger** [comment]
ok
