### ISSUE TITLE
Go Back from link by reading system use case

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/ebraille#16]
As a user, I want to follow an internal link to another location in the book and easily go back to the exact location where I started.

Problem statement:  While reading, a person wants to follow an internal link to a reference such as a footnote, a bibliographic reference , a glossary term, etc. However, the reader then wants to return to their exact location to continue reading. While it is possible to encode a back link to an exact location, this only works if there is one reference to that item. For example, a single glossary term may be linked from several places in the book. It is not possible to encode a back link in this case. Also, it is much more time consuming to encode back links in content.

It it should be a requirement of reading systems to have a "go back" function. The reading system would store the current exact location and then follow the link and allow the user to read through the passage and then use the go back function to get to where they started. It would also be possible for the reading system to store more than one of these locations to create a history thread. For example, a user follows a link to a reference, which also contains a link. In this case, the user would need to go back twice to get to their original location.

**Comment by wfree-aph** [comment]
This is a reading system feature but the use of the EPUB packaging format should make it easier to implement and it certainly makes it possible. Closing this issue.
