### ISSUE TITLE
Lists and Nested lists, calculating indents

### ISSUE THREAD

**Issue by GouldenJen** [daisy/ebraille#162]
Submitted to the email list by James Bowden:
For some list structures, the indentations required for overrun lines may depend on the maximum hierarchy level of the entire list. This applies to, for example:
•	Lists of various kins in BANA format
•	Tables of contents in UK (and other) formats
•	Indexes in UK (and other) formats

For example, in a BANA format list:
•	For single hierarchy (only one level): each point starts in cell 1 with runover lines in cell 3.
•	For double hierarchy (two levels of list point), top level items start in cell 1 with runovers in cell 5; subitems start in cell 3 with runovers in cell 5.
•	For triple level, it would be: top level items start in cell 1 with runovers in cell 7; subitems start in cell 3 with runovers in cell 7; sub-subitems start in cell 5 with runovers in cell 7.

Below are three possible options for consideration how eBraille might tag up nested lists so correct indentation may be achieved.

### Option 1: every list item should carry a class
In this method, every individual list item carries a class giving the required indentation. I think this is in fact the way some transcribers may ensure correct indentation currently.

We could set the default (no class) to be the "most common" case of a single level list - thus default to 1-3.

So, for example, an ordinary list with no nesting would just be:
<ol>
    <li>item 1 text</li>
    <li>item 2 text</li>
    ...
</ol>

A nested list would look like this:

<ol>
    <li class="1-5">item 1 text</li>
    <li class="1-5">item 2 text</li>
    <ol>
        <li class="3-5">item 2.1 text</li>
        <li class="3-5">item 2.2 text</li>
    </ol>
</ol>

The classes are the specific numeric ("generic") classes as mentioned in the Tagging Best Practice. (Note perhaps a better word than "generic" might be better here, but that's another issue).

### Option 2: The top level list should carry a class
In this option, it is the list structure, rather than individual items that carries a class indicating the number of levels
(This is what we do for indexes and tables of contents at RNIB with Duxbury styles.

A simple list would look the same as above.

A nested list would look like this:

<ol class="list2levels">
    <li>item 1 text</li>
    <li>item 2 text</li>
    <ol>
        <li>item 2.1 text</li>
        <li>item 2.2 text</li>
    </ol>
</ol>

### Option 3: Like Duxbury's MFCS
There is a little-known code in Duxbury Braille Translator, mfcs. I don't fully understand all the possibilities of this code but I understand that it scans through the structure it encloses to find out the maximum hierarchy level and formats accordingly.

From Peter Sullivan:
The intent of “Duxbury MFCs” is essentially the same as a class attribute in HTML: it is an a definition offloaded to elsewhere, like a CSS.

Option 2 would make the most sense, if the list formatting indent by level could be captured in a CSS. Likewise, use of an MFC generally implies widow/orphan protection for each “list item” or other “paragraph” within the MFC. Produces best results from a class attribute if that also was in the CSS.

James Bowden:
A new tag could be invented to alert the Reading System it needs to do calculations.

The single level list is as above, the multilevel list then looks like this:

<@multilevel> ← custom tag to do the calculation
    <ol>
        <li>item 1 text</li>
        <li>item 2 text</li>
        <ol>
            <li>item 2.1 text</li>
            <li>item 2.2 text</li>
        </ol>
    </ol>
</@multilevel>

### Comparison
Option 1, tagging every list item is perhaps the simplest for Reading Systems, because each item carries the required format. However it would bloat file size and possibly gives authors extra work to do to make sure every individual item is tagged properly.

Option 2 gives the author one place to say the list hierarchy maximum. The rest is relatively straightforward. The formatting could equally be put in a <div> around the multilevel list structure, keeping the actual list coding clean.

Option 3 means we invent a new custom tag and have to write associated code. However, it frees authors from any complexity.

Option 1 would be maximum work for authors, minimum work for reading systems; option 3 would be maximum work for reading systems and minimum work for authors; option 2 would be somewhere in-between.

### Option 4
Bert Frees Proposes a Fourth Option:
There is a fourth option, namely the relational pseudo-class ":has()" in CSS, see https://www.w3.org/TR/2022/WD-selectors-4-20221111/#relational.

With this CSS feature, no additional markup is needed. CSS rules can use the :has() pseudo-class to find out whether the list contains nested lists, like this:

    ol:has(ol) {
        /* this is a nested list */
    }

The BANA style sheet would look something like this:

    li {
       text-indent: -2ch;
       margin-left: 2ch;
    }
    ol:has(ol) > li {
       text-indent: -4ch;
       margin-left: 4ch;
    }
    ol ol li {
       text-indent: -2ch;
       margin-left: 0;
    }

(Note that this is the simplified version: it assumes that the nesting is not more than 1 level deep).

The drawback of the :has() pseudo-class is that although it is supported in modern browsers, it is possible that some people use a browser that doesn't support it yet. (But of course, this only needs to be a consideration if we want to target browsers.)

**Comment by bertfrees** [comment]
This should now be covered in the [eBraille Styling Best Practices, under the section "Indentation"](https://daisy.github.io/ebraille/best-practices/styling/index.html#indentation). If you think there are still things missing or not explained well enough, please feel free to reopen the issue.
