### ISSUE TITLE
brl:producedDate instead of brl:created

### ISSUE THREAD

**Issue by franciscoONCE** [daisy/ebraille#168]
This would follow Daisy's metadata dtd:producedDate. This is a proposal for a name change only, not its contents.

**Comment by wfree-aph** [comment]
At June 25, 2024 meeting: Suggested to dc:date. Objection to that change is that brl:producedDate would be clearly referring to the braille file. EPUB refers to dc:date as being about the resource itself, so not back to the original print but, in this case, would refer to the braille file.

Group ultimately agrees to use brl:producedDate.
