### ISSUE TITLE
NEW brl:sourcePublisher instead of dc:source

### ISSUE THREAD

**Issue by franciscoONCE** [daisy/ebraille#169]
dc:Source has been defined to include the source publisher's name, but it should contain an ID for the source document (i.e., an ISBN number). The name proposed comes from the Daisy specification: dtd:sourcePublisher.

**Comment by nicolegaines** [comment]
I agree. I would also recommend that dc:Source be used for the source book ISBN and be required in the metadata, if applicable, and repeatable for as many ISBNs as refer to the identical content (e.g., softcover, hardcover).

**Comment by wfree-aph** [comment]
At the June 25, 2024 meeting: There is general agreement with this idea.

**Comment by mattgarrish** [comment]
Closing this issue as this was addressed in https://github.com/daisy/ebraille/pull/217
