### ISSUE TITLE
Control over Formatting Indicators (eg italics, boldface)

### ISSUE THREAD

**Issue by mrhunsaker** [daisy/ebraille#17]
As a braille reader and teacher, I see a great benefit to having control over the amount of formatting a braille file shows me (or a student)

*Detail*
There are times that Typeform indicators can make the reading of text difficult for learning braille readers (and sometimes for veteran readers as well). The example that comes to mind is a textbook a student is currently using provides italics, boldface, and a color indicator (as transcriber-defined typeform indicator 1). Unfortunately, the textbook used all of these typeform features in meaningful ways.  For the vision-impaired student, this information was distracting and required significant effort.

*Proposal*
Understanding that it is important for ebraille to reflect what was in print (particularly for textbooks and other materials where formatting is used functionally and not just for aesthetics), there also should be an ability to limit how much emphasis is provided. One can envision an option to "remove emphasis", "some emphasis" akin to just saying text was emphasized rather than giving the detail, and "full emphasis" wherein a reader may encounter Bold, Italicized, colored text (i.e., with transcriber defined typeform indicators)

**Comment by jrbowden** [comment]
This is the same as #14.
Taken to extreme, one could define all kinds of show/hide parameters:
- italics/bold/underline
- capitals
- unusual symbols
- graphics / alt text / long descriptions for images
- in music, all kinds of articulations, fingering, expressions, clefs, special signs etc, ...

The list could go on.

All possible, but we will need to decide how much is desirable, easily achievable, producible by transcribers, devices, users etc.

**Comment by wfree-aph** [comment]
This feature will depend on authors and reading systems taking advantage of the markup made available but emphasis is covered in the [Tagging Best Practices](https://github.com/daisy/ebraille/blob/main/best-practices/tagging/index.html) document, so I will close this issue as resolved.
