### ISSUE TITLE
dc:Creator with role attributes

### ISSUE THREAD

**Issue by franciscoONCE** [daisy/ebraille#170]
As it happens with the Daisy tag of the same name, it would be useful to include an attribute that specifies its role in the document, i.e., translator, illustrator, editor, compilator, etc.

Matt explains how this can be done:

The package document supports adding roles, but not through an attribute. It uses a “refines” attribute that references the creator element. Here’s an example from the epub 3 specification using marc relators:

```
<dc:creator id="creator01">Lewis Carroll</dc:creator>
<meta refines="#creator01" property="role" scheme="marc:relators">aut</meta>
```

You can do similarly for contributors. For example, for someone who helped create the ebraille file you might specify:

```
<dc:contributor id="contrib01">Jane Doe</dc:contributor>
<meta refines="#contrib01" property="role" scheme="marc:relators">mrk</meta>
```

dc:Contributor is not in our list at this point, but we might consider including it as well if there's interest. I find it useful.

**Comment by egli** [comment]
We should probably close this issue as the discussion was not about the creator of the original print publication but more about the creator of the eBraille. I opened a new issue for a `brl:contributor` meta data, see #203
