### ISSUE TITLE
dc:Identifier clarification

### ISSUE THREAD

**Issue by franciscoONCE** [daisy/ebraille#171]
In the description that we have now it is not clear if this identifier refers to the source document or the braille transcription. It should be made clear that it refers to the latter.

**Comment by wfree-aph** [comment]
As discussed at the June 25, 2024 meeting: Required by EPUB 3.3 but not required to be about the print book as Willow was originally thinking. It can be about the braille transcription and this would align with what DT Book does. So we would use dc:source for the ISBN and then could use this to refer to the eBraille file.

Question of whether there is a way to confirm if an identifier is unique. Having a unique identifier there may be more difficult than it seems. There are tools that generate random numbers that end up being unique. The primary use is for the reading system and you won't have millions of books on that reading system, more like hundreds. Could put the acronym of the organization before the string of numbers and that would ensure it was unique. You could also use the ISBN and then append your organization to the end of that. RNIB uses RNIB_ and then the UUID. ONCE has a production number and it is a unique number for that braille book and you could also have an ISBN of the braille book that is different than the original publication. The main qualification is that it be unique. More then may come out of this later.

**Comment by egli** [comment]
You can use a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) , a Universally unique identifier to make sure that you have a unique identifier for the eBraille that you are producing. UUIDs can be generated automatically and are almost certainly unique (statistically speaking you will have to generate 1 billion UUIDs per second for about 86 years, before you will get the same UUID)
