### ISSUE TITLE
Cannot link to PDFs without fallbacks

### ISSUE THREAD

**Issue by mattgarrish** [daisy/ebraille#172]
I noticed for PDF graphics that the tagging recommendation is currently to use a hyperlink with a download attribute:

`<a href="/images/butterfly.pdf" download>⠠⠛⠗⠁⠏⠓⠊⠉⠀⠷⠀⠁⠀⠃⠥⠞⠞⠻⠋⠇⠽</a>`

Unfortunately, since we're following epub's file rules, this isn't valid without a manifest fallback. Using a hyperlink requires the PDF to be listed a non-linear document in the package document spine, which in turn requires the fallback (the download attribute has no meaning in epub).

Making this valid epub is going to require a lot of work for publishers, or else we have to superset epub to allow PDFs without fallbacks, in which case ebraille file sets won't always be conforming epub file sets (and ebraille publications may not always open in epub reading systems). There's also no guarantee the file will be downloadable out of the container - it will depend on system security restrictions.

A simpler solution would be to use the `object` element to embed the PDF graphics. For example:

```
<object type="application/pdf" data="images/tactile.pdf" width="100" height="100">
            <p>Alt text description.</p>
</object>
```

This doesn't run afoul of epub's core media type requirements as the body of the object tag serves as the fallback.

**Comment by avneeshsingh** [comment]
We should test accessibility for using object for pdf.

**Comment by mattgarrish** [comment]
> We should test accessibility for using object for pdf.

I expect this is going to require a reading system before we can meaningfully check how it works. I'm going to close this issue for now, though, as we have an editor's note in the spec that we need to verify this method.
