### ISSUE TITLE
Control over Contracted - Uncontracted braille

### ISSUE THREAD

**Issue by mrhunsaker** [daisy/ebraille#18]
As a braille user and teacher, I see a benefit in having control over the level of contraction present in braille

*Details*
When I am working with adults and students that are learning braille, it is helpful to have access to uncontracted versions of materials in UEB. Even at times, braille learners that are in the process of becoming comfortable with contracted braille can use uncontracted braille for leisure reading, or to confirm they were reading contracted braille correctly. 

*Proposal*
As a digital format can contain multiple files, it seems possible to have an uncontracted and contracted file(s) available that can be selected by the end user. (Note, I am not necessarily a fan of learning tables, so in no way would I advocate having multiple files for each step of a learning curriculum, this should be done by the vision specialist/teacher and provided to the learner).

**Comment by jrbowden** [comment]
I think you are asking for multiple files of the same text to be included in the package?
Not only could one have fully contracted and fully uncontracted, but, if following a particular braille learning scheme, then one could include multiple files, each translated according to each level of the learning scheme, giving graduated levels of contraction between fully uncontracted and fully contracted.

In fact, German braille has three standards: fully uncontracted (not often used), a few contractions (I think called Vollschrift) and fully contracted (Kurzschrift).

Alternatively, I think you are asking for the print original to be stored in the package and then on-the-fly transcription?

**Comment by avneeshsingh** [comment]
It looks the use case is mainly about ability to package set of files for different level of contraction in the same package and providing sufficient hooks for the reading device to select the right contraction and present it to the user.

What should be the priority of this use case. 
Even if this requirement is not met by the first version of specification, braille production houses can create different file sets for different levels of contraction and make them available to users.

**Comment by mrhunsaker** [comment]
@jrbowden I would like to avoid at all costs transcription on the fly, the formatting is never right, and it is sufficiently incorrect that it is often a major problem. I fight people who suggest JAWS and NVDA's OCR is more than sufficient so braille transcribers are unnecessary. Your first comment actually precisely states what I ham-handedly tried to convey.

**Comment by mrhunsaker** [comment]
I would say medium or low priority. I see it as important as an educator, but there are a great many other issues that should take priority.

**Comment by mattgarrish** [comment]
EPUB lets you package more than one rendition in the zip file, but reading systems have never adopted the attributes for selecting between them. That's largely because mainstream publishers have yet to find a compelling case for putting two formats together (they would distribute the renditions separately).

Bundling renditions together is much less problematic than switching between them. Absent a mapping document, the only way it can work is if everything between the renditions is the same - same ordering in spine, same file naming, same elements in the dom (and probably other restrictions).

HTML might be able to offer a solution here using the `link` tag with `rel=alternate`. But that's if it's possible to express the formatting of the alternate page as a language.

**Comment by GeorgeKerscher** [comment]
I know that the focus is on shipping the encoded braille instead of  text that is encoded on the fly, but the text would allow TTS, and whatever version of contracted or uncontracted braille one would want, all done on the fly.

**Comment by jrbowden** [comment]
Adding ordinary print may give additional TTS options, but be aware it may also make publishers much more uneasy about the format because it could then potentially be used by the public at large.
Out of interest, if there was a plain text rendition, what should it contain for non-literary text content: e.g. math, music?

**Comment by GeorgeKerscher** [comment]
MathML is what I would expect for the Math. This is supported in all the formats we are considering.

Here in the US, we have not had a problem with the distribution of EPUB through Bookshare. It is not encrypted, but it is watermarked and fingerprinted. These do not impact the processing in reading systems.

Music is interesting. Is it MusicML that is used in the Music Braille project? We can check in with Sarah who heads up the project.

**Comment by bertfrees** [comment]
> HTML might be able to offer switching using the `link` tag with `rel=alternate`, but that's if it's possible to express the formatting of the alternate page as a language. 

See my comment in https://github.com/daisy/ebraille/issues/25#issuecomment-1273256658.

**Comment by jrbowden** [comment]
@GeorgeKerscher  Music XML is the current format for music.
Note that using both Math ML and Music XML would mean the reading system would need to do a lot of work to create a TTS rendition, though of course with rich XML data, a lot of navigational possibilities exist.

**Comment by wfree-aph** [comment]
The EPUB packaging format makes this feature technically possible. It won't necessarily be easy and it will require authors and reading systems to utilize the feature that @mattgarrish mentions in his comment but I am not sure what else we could at this stage in the spec writing process. I am going to close this as resolved but please reopen if you take issue with that decision and provide suggestions for how the spec could be improved to make this feature better or easier to implement.

**Comment by egli** [comment]
@wfree-aph I presume you are talking about the multiple renditions feature that could be used t implement both contracted and uncontracted braille in one publication. I had not thought of that, but that is certainly a possibility.

**Comment by wfree-aph** [comment]
@egli, yes that is what I was thinking. Sorry my comment wasn't more specific. I'm not saying that solution is ideal but it's the only one that is really feasible without major changes to the specification. By making the spec braille-first, we've basically locked ourselves into this solution. It is true that you could have braille and print and that the print could technically be translated into whatever was needed, you basically need braille to call it an eBraille file at this stage and that braille will be hardcoded for contracted or uncontracted, so you'll always need the braille plus something else, whether that is a different version of braille or some kind of print, if you want to have multiple codes or grades.
