### ISSUE TITLE
brl:completeTranscription as a set of values instead of true false

### ISSUE THREAD

**Issue by egli** [daisy/ebraille#197]
It might be better to rename `brl:completeTranscription` to something like `brl:transcriptionStatus` and have a controlled set of values like
- complete
-  partial
- etc

**Comment by mattgarrish** [comment]
This sounds like you'd be changing the property from a statement about whether the full content is transcribed to a statement about whether the transcription process itself is completed or not. Is that what you're intending here?

**Comment by egli** [comment]
I don't really have a strong opinion here. I just thought there might be more values than just true false. 

OTOH, I don't really want some value to indicate the transcription process. I think we can assume that the transcription process is finished once the eBraille publication is out. Then the question is really just: is it a complete or a partial transcription? And for that the boolean value as originally intended seems perfectly fine.

**Comment by mattgarrish** [comment]
Naming it the "status" of the transcription is what worries me. That suggests it's describing the process of transcribing. You could do incremental updates of a publication by publishing new releases with more content, so partial might not mean a complete transcription isn't coming.

It sounds like you want something like dcterms:extent or dcterms:coverage, but the former is defined as providing file size or duration and the latter for spatial and temporal statements. I don't know if it would be valid to reuse either for more generic coverage statements.

**Comment by egli** [comment]
No, no. I certainly do not want a status.  I also think that neither `dcterms:extent` nor `dcterms:coverage` convey the meaning we are trying to bring across here.

So let's go back to `brl:completeTranscription` as it currently is defined.

**Comment by wfree-aph** [comment]
@egli and @mattgarrish, when this idea was initially discussed, the concern was that trying to have a more specific, granular value for this metadata term would be confusing and by sticking with true and false, it's clear that the transcription is either complete or it isn't. I think that serves the need to quickly identify completed transcriptions vs ones that are not completed and ones that are not completed could be further investigated by the user.

**Comment by mattgarrish** [comment]
Closing this as it sounds like the consensus here is to leave the property as it is. Please re-open, though, if you think it needs further consideration.
