### ISSUE TITLE
Add dc:Date

### ISSUE THREAD

**Issue by egli** [daisy/ebraille#199]
According to the [Specifications for the Digital Talking Book](http://www.daisy.org/z3986/2005/Z3986-2005.html):

> dc:Date
> Date of publication of the DTB. (Compare dtb:sourceDate and dtb:producedDate.)
> Occurrence: Required

**Comment by mattgarrish** [comment]
This matches how dc:date is already defined for epub. It's available as an optional metadata element, so it would be better to use it and make it recommended unless the transcription completion date is important to capture.

If we keep everything existing and being proposed, we'd have:

- a11y:sourceDate - date the source publication was published
- a11y:created - when the transcription was completed
- dcterms:modified - last time any part of the ebraille publication was modified (metadata, css, content, etc.)
- dc:date - when the ebraille publication was published

It could be they are all necessary, but a11y:created seems more like production metadata than bibliographic or end user metadata if we keep all these. (It could also use a better name, like transcriptionDate.)

**Comment by mattgarrish** [comment]
Closing this as we made dc:date required for the publication date in https://github.com/daisy/ebraille/pull/267
