### ISSUE TITLE
Include Braille Code in Metadata

### ISSUE THREAD

**Issue by mhorspool** [daisy/ebraille#20]
As a Reader I would like to know the braille code in which the file is transcribed before I open it so that I can quickly decide whether it will be suitable for me to read.

**Comment by jrbowden** [comment]
I suggest this is combined with #19 so the the metadata should include the code and grade.

**Comment by ways2read** [comment]
metadata issues are grouped under #27

**Comment by bertfrees** [comment]
I don't know of any standard that provides a list of existing braille systems. Is that also part of this requirement?

**Comment by mhorspool** [comment]
It's a good point. We need a standardised list of codes otherwise we could end up with "UEB", "Unified English Braille", "English Unified", "English UEB" etc all being used, which would make it useless for search/filter.

There are already standards for specifying languages. We could use those and extend as necessary. It needs further thought though.

**Comment by mattgarrish** [comment]
The same comments I made in https://github.com/daisy/ebraille/issues/27#issuecomment-1271789758 and https://github.com/daisy/ebraille/issues/25#issuecomment-1271809234 apply here.

**Comment by bertfrees** [comment]
See my comment in https://github.com/daisy/ebraille/issues/25#issuecomment-1273256658 about specifying the braille code in a BCP 47 language tag.
