### ISSUE TITLE
Maybe add brl:revision, brl:revisionDate and brl:revisionDescription

### ISSUE THREAD

**Issue by egli** [daisy/ebraille#202]
According to the [Specifications for the Digital Talking Book](http://www.daisy.org/z3986/2005/Z3986-2005.html):

> dtb:revision
> Non-negative integer value of the specific version of the DTB. Incremented each time the DTB is revised.
> Occurrence: Optional. Not repeatable.
>
> dtb:revisionDate
> Date associated with the specific dtb:revision. In format from [[ISO8601]](http://www.daisy.org/z3986/2005/Z3986-2005.html#ISO8601)
> Occurrence: Optional. Not repeatable.
>
> dtb:revisionDescription
> A string describing the changes introduced in a specific dtb:revision.
> Occurrence: Optional. Not repeatable.

I'm not sure how useful this is. It is contained in the DTB spec, but if it is used in practice I do not know. We at SBS do not use it.

**Comment by mattgarrish** [comment]
I don't know if there's a lot of value in having these. I remember there was a request to add revision history metadata to epub, but the response was that even if publishers keep track of this information it's not something they want to store in the package metadata. If it's for production workflow purposes, they need the info in their internal systems, and if it's for user consumption then it would be part of the publication text and not locked away in the package metadata where reading systems won't expose it. I imagine the same would be true here.

**Comment by mattgarrish** [comment]
If someone really needs these, they could also define a prefix for the dtb vocabulary and pull them in themselves.

For example:

```
<package ... prefix="dtb: https://www.daisy.org/z3986/2005/dtbook/">
   <metadata>
      ...
      <meta property="dtb:revision">x.x</meta>
      ...
   </metadata>
   ...
</package>
```

**Comment by egli** [comment]
> If someone really needs these, they could also define a prefix for the dtb vocabulary and pull them in themselves.

Sounds reasonable.

I think we probably close this issue then

**Comment by mattgarrish** [comment]
Closing this issue as noted.
