### ISSUE TITLE
Include Producer Name in Metadata

### ISSUE THREAD

**Issue by mhorspool** [daisy/ebraille#21]
As a Reader I would like to know whether the braille in the file has been transcribed by a human or computer before I open it so that I can assess the likely accuracy of the transcription. This facility could be implemented with a 1-bit flag, but I think it would be more desirable to include the full name of the producer of the file so that house style etc can also be predicted. For automated transcriptions, the name of the automated transcription tool could be included in the producer field.

**Comment by mrhunsaker** [comment]
I think this can easily be included in any file metadata. I see this as particularly important for technical and math materials that are often poorly transcribed by automated processes.

**Comment by mhorspool** [comment]
Further to comments in #22 , I would also suggest adding "producer location" to this section of metadata to further improve predictability of layout style.

**Comment by ways2read** [comment]
metadata issues are grouped under #27

**Comment by mattgarrish** [comment]
The same comment I made in https://github.com/daisy/ebraille/issues/27#issuecomment-1271789758 applies here.
