### ISSUE TITLE
Creator name formatting

### ISSUE THREAD

**Issue by mattgarrish** [daisy/ebraille#218]
I noticed that the dc:creator examples have the last name first followed by a comma. For example:

```
<dc:creator id="aut01">
   Brontë, Charlotte
</dc:creator>

<dc:creator id="aut02">
   Melville, Herman
</dc:creator>
```

If a reading system merges these using commas in the bookshelf, however, the user would likely be presented with:

>    Brontë, Charlotte, Melville, Herman

This could get confusing to read. Is it necessary to format the names this way, or can we use the file-as property to provide sorting information? For example:

```
<dc:creator id="aut01">
   Charlotte Brontë
</dc:creator>
<meta property="file-as" refines="#aut01">Brontë, Charlotte</meta>
```

**Comment by wfree-aph** [comment]
@mattgarrish Using the file-as property makes sense to me. Thanks for pointing out this issue.
