### ISSUE TITLE
Include Page Layout Information in Metadata

### ISSUE THREAD

**Issue by mhorspool** [daisy/ebraille#22]
As a reader/producer I would like to know the characters per line and lines per page envisaged by the producer of the file so that, if I have matching paper, I can emboss it as designed. I would also like to know whether any special spacing was envisaged, e.g. double line spacing.

**Comment by jrbowden** [comment]
Would it also be useful to know the general braille layout standard, e.g. BANA, UKAAF, Germany etc?

**Comment by mhorspool** [comment]
I see what you're saying but I'm inclined not to go down that route, as it implies that everyone will comply with a recognised standard. Whilst we hope that this will be the case, smaller/independent transcribers (e.g. Torch) might deviate to one extent or another.

I think including the producer #21 will imply everything that needs to be implied about standards. I will leave a comment in there to follow that thought through.

**Comment by ways2read** [comment]
metadata issues are grouped under #27

**Comment by mattgarrish** [comment]
The same comment I made in https://github.com/daisy/ebraille/issues/27#issuecomment-1271789758 applies here.

**Comment by GouldenJen** [comment]
GitHub Ticket: #41 
Requested metadata: Recommended braille layout:
Lines per page
NLS Dublin core Element: x-metadata brl:pageLength
Notes from GitHub ticket: Reflects the recommendation of the braille producer and does not limit the file to the layout specified.
Lack of consensus on whether to include braille standard (e.g., BANA, UKAAF)?
Notes from metadata team: Reflects the recommendation of the braille producer and does not limit the file to the layout specified.
Lack of consensus on whether to include braille standard (e.g., BANA, UKAAF)?

**Comment by GouldenJen** [comment]
GitHub ticket: #41
Requested metadata: Recommended braille layout:
Cells per line
NLS Dublin Core element: x-metadata brl:lineLength
Notes from GitHub ticket: Reflects the recommendation of the braille producer and does not limit the file to the layout specified.
Lack of consensus on whether to include braille standard (e.g., BANA, UKAAF)?
Notes from metadata team: NLS does not appear to have metadata related to line spacing?
brl:pages refers to the total number of embossed braille pages in the BRF file.

**Comment by GouldenJen** [comment]
GitHub ticket: #41
Requested metadata: Recommended braille layout:
Line spacing (single, double, etc.)
NLS Dublin Core Element: N/A
Alternative dc or schema.org: x-metadata brl:lineSpacing?
Notes from GitHub ticket: Reflects the recommendation of the braille producer and does not limit the file to the layout specified.
Lack of consensus on whether to include braille standard (e.g., BANA, UKAAF)?
Notes from metadata team: NLS does not appear to have metadata related to line spacing?
brl:pages refers to the total number of embossed braille pages in the BRF file.

**Comment by wfree-aph** [comment]
Just like #110, this issue can be closed because the necessary information is included in [first draft of the specification](https://github.com/daisy/ebraille/blob/main/index.html).
