### ISSUE TITLE
Reserved class names without any restrictions make no sense

### ISSUE THREAD

**Issue by bertfrees** [daisy/ebraille#227]
If a class name can be anything (any valid CSS identifier), what does it mean to "reserve" it? For example:

- For boxed text: on `div`: _various strings_

   The explanation in the text is:

   > Various strings can be used for boxes with specific text needs. Examples could include boxes with color. There is no way to define all possible strings that could be used in such a scenario. The writing software will need to define the limitations and allow the user to input the string, which is then used as the class to allow the CSS to input that string into the box line.

   This is correct, but shouldn't writing software allow the user to define new classes _anyway,_ for potentially _any_ element? It is good to include the examples of colored boxes, but it makes no sense to add "various strings" to the reserved class names because 1. what does it mean to "reserve various strings", and 2. we could add it everywhere.

**Comment by mattgarrish** [comment]
Are you wanting to define a prefix we reserve for classes we define? For example, class names that start with brl- are reserved for this group to define?

**Comment by bertfrees** [comment]
That is what @egli [suggested](https://github.com/daisy/ebraille/issues/144).

I was not thinking of this when I created the issue, but it could indeed make sense to do it.

**Comment by mattgarrish** [comment]
It would make accidental collisions with author styles less likely. Authors wouldn't have to know all the class names to avoid in the best practices guide, or have to worry that names they use now may be taken away in the future; they would only have to know never to start any of their own class names with brl-.

**Comment by clapierre** [comment]
I think this is a good idea to have pre-defined "brl-" class names for our reserved classes.

**Comment by wfree-aph** [comment]
My thinking here was that the user would use various strings to indicate which color was being used. I can see the point with this ticket though. I will remove "various strings" from the reserved class values section. What's the best way to handle the tagging of boxes that have color? The reading software will need to know the color, so we'd need some way to indicate colors like blue, red, etc. Is having the color be one of the class names suitable or is there a better way?
