### ISSUE TITLE
Double check BANA examples in styling best practices for correctness

### ISSUE THREAD

**Issue by bertfrees** [daisy/ebraille#229]
@wfree-aph Can you please check the following examples:

- [x] [Centered heading split onto multiple lines](https://daisy.github.io/ebraille/best-practices/styling/#example-centered-heading-split-onto-multiple-lines): the automatic balancing seems more optimal. Add [`?developer-mode=true`](https://daisy.github.io/ebraille/best-practices/styling/?developer-mode=true#example-centered-heading-split-onto-multiple-lines) and click on "Validate" when hovering the expected formatted braille to check the automatic balancing.
- [ ] [Line numbered prose](https://daisy.github.io/ebraille/best-practices/styling/#example-line-numbered-prose): the desired layout does not seem entirely consistent with the standard: the word at the beginning of the third line could also fit at the end of the second line.

**Comment by wfree-aph** [comment]
@bertfrees Sorry for the delay. That word does not fit because you need to reserve enough space for the longest line number and two spaces on every line, even ones that don't have a line number on them. That's a part of line number prose rules in North American braille formatting.

For the centered heading question, I agree that automatic balancing is better. Is there anything else I need to do here other than update the tagging document?

**Comment by bertfrees** [comment]
> That word does not fit because you need to reserve enough space for the longest line number and two spaces on every line

Yes, but there were 11 available cells on that second line, so just enough for one extra word of 8 cells (⠢⠞⠻⠏⠗⠊⠎⠑), with one empty cell before it and leaving two empty cells after it (before the line number). But after [changing the braille examples to uncontracted](https://github.com/daisy/ebraille/pull/234), the issue has solved itself.

For the automatic balancing, apart from updating the tagging guidelines (https://github.com/daisy/ebraille/issues/211), the expected formatted braille of the example should also be updated. Instead of this:

```
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠁⠀⠉⠑⠝⠞⠑⠗⠑⠙⠀⠓⠑⠁⠙⠊⠝⠛⠀⠎⠏⠇⠊⠞⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠕⠝⠀⠍⠥⠇⠞⠊⠏⠇⠑⠀⠇⠊⠝⠑⠎⠀⠺⠊⠞⠓⠀⠞⠓⠑⠀⠙⠊⠧⠊⠎⠊⠕⠝⠎⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠓⠁⠏⠏⠑⠝⠊⠝⠛⠀⠁⠞⠀⠇⠕⠛⠊⠉⠁⠇⠀⠏⠕⠊⠝⠞⠎⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
```

the heading could also be broken like this (one word moved from the second line to the first), which is slightly more optimal (more compact), and what `text-wrap: balance` does:

```
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠠⠁⠀⠉⠑⠝⠞⠑⠗⠑⠙⠀⠓⠑⠁⠙⠊⠝⠛⠀⠎⠏⠇⠊⠞⠀⠕⠝⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀ ⠀⠍⠥⠇⠞⠊⠏⠇⠑⠀⠇⠊⠝⠑⠎⠀⠺⠊⠞⠓⠀⠞⠓⠑⠀⠙⠊⠧⠊⠎⠊⠕⠝⠎⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠓⠁⠏⠏⠑⠝⠊⠝⠛⠀⠁⠞⠀⠇⠕⠛⠊⠉⠁⠇⠀⠏⠕⠊⠝⠞⠎⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
```
