### ISSUE TITLE
Meaning of form-feed characters in braille content

### ISSUE THREAD

**Issue by jasonjgw** [daisy/ebraille#238]
Section 6.2.1 of the public draft specifies that form-feed characters are allowed in braille content, but it doesn't specify the interpretation. Should the reading system treat a form-feed as a hard page break (which would only make sense for an embosser or a multi-line display)?

**Comment by mattgarrish** [comment]
The form feed character needs to be removed from that list and the reference changed from infra to xml in a future update.

EPUB had a similar reference to the infra whitespace definition, but form feed isn't a valid xml whitespace character per xml. It will halt the parser if it occurs in an xhtml file.

I've just gone through getting epub fixed, so we need to make the same change here.
