### ISSUE TITLE
Metadata to reflect publication date

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#263]
Publication date and copyright date may be different, so it is possible that both are needed. Creating this issue in order to close #27 and #124 with a more specific issue. Everything else mentioned in those issues is already reflected in the spec.

#124 suggests date.Issued from NLS but there is also [dc:date](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/date) which is more general but could be used to meet our needs.

**Comment by mattgarrish** [comment]
EPUB already [reserves dc:date for the publication date](https://www.w3.org/TR/epub-33/#sec-opf-dcdate). We could list that as a required property (it's optional in EPUB).

And we have dcterms:dateCopyrighted listed in the specification for the copyright date.
