### ISSUE TITLE
Include general information about document in metadata

### ISSUE THREAD

**Issue by jrbowden** [daisy/ebraille#27]
As a user I would like to know information about the book without having to fully open it.
As a library, I would like to know full information about the book without having to read it.

The filename of a book may only give partial information, or be of no practical use (if for example it is a job or work number).

The book information could be included in metadata and could include:
- Title
- Author
- Publisher
- Published date
- ISBN
(Full list to be agreed)

Plus, metadata could include any braille-related metadata as shown in other use cases, such as #19 #20 #21 #22 #25

**Comment by franciscoONCE** [comment]
For a more or less complete list, we could rely on existing standards in use, such as Marc 21 or Dublin Core. The list of metadata elements provided by the NLS could be a good starting point. Link to this NLS list here - https://www.loc.gov/nls/about/organization/standards-guidelines/contract-specifications/braille-oeb-package-file-bopf-requirements-2022/#bopf-metadata

**Comment by mattgarrish** [comment]
Being able to express metadata is pretty universal to all the publishing formats. There are limitations to the expressive of each format, though, so here it would help to know whether simple, unassociated metadata statements are all that's needed or whether more complex metadata is expected.

- DTBook only allows dublin core metadata and meta elements by default without a means of making associations.
- EPUB includes the same metadata elements but also has a "refines" attribute to tie expressions together (although this attribute is often regarded as something of an abomination).
- HTML is arguably the richest of the group, even if its meta tag is pretty rudimentary. You can embed JSON-LD metadata records, for example, or you can use RDFa or microdata in the body.
- The publication manifest format is one big JSON-LD record (sort of an advanced form of the epub package document).

**Comment by GouldenJen** [comment]
- GitHub ticket: #41 
- Requested metadata: Source document information: title
- NLS Dublin Core element: dc:Title

**Comment by wfree-aph** [comment]
Closing this issue in favor of a more specific issue that reflects the remaining need, which is #263.
