### ISSUE TITLE
Review the list of braille codes before making them officially "registered"

### ISSUE THREAD

**Issue by bertfrees** [daisy/ebraille#289]
There hasn't been a chance to properly review the [list of "registered braille code"](https://daisy.github.io/ebraille/registries/codes/#registered-codes) that was compiled by Willow. It more or less came from the list of translation tables in Liblouis, so it has some legitimacy, but the codes haven't been reviewed by anyone with some form of authority.

Here is one example that shows that the list hasn't been reviewed properly:

> <dl><dt>Japanese Kantenji UCS2</dt><dd>Kantenji-UCS2 grade0</dd></dl>

This is a Liblouis specific thing: "UCS2" means that a translation table is intended to be used with a version of Liblouis compiled for 16-bit computing. In other words, it has nothing to do with a braille system.

So I think it is more appropriate to call them "candidates" (if at all we want to already include them in the spec).

I suggest we either

- drop the list from the spec, and explain that no codes has been registered yet
- have something along these lines:

   <h2>3. Registered codes</h2>
   <p>No codes has been registered yet.</p>
   <aside>
      <h4>EDITOR'S NOTE</h4>
      <p>Below is a list of submitted codes that are currently being reviewed. It is included here in order to show what the code registry could look like.</p>
      <dl>
         <dt>Afrikaans grade2</dt>
         <dd>Afrikaans contracted</dd>
         ...
      </dl>
   </aside>

**Comment by mattgarrish** [comment]
I wonder if we could have two sections: proposed and registered. That would allow us to incubate proposals in the future before accepting them fully into the registry. Incubating proposals in github issues often means no one sees them until they're integrated.

That would allow us to move everything we have now into the proposed section (although as a draft document we could argue that nothing in this document is official).

**Comment by bertfrees** [comment]
Yes good idea. Two sections would work I think. Makes things more transparent.

> although as a draft document we could argue that nothing in this document is official

Yes I realized that, but still, the title "Registered codes" gives the impression that they at least have been reviewed.
