### ISSUE TITLE
Reading Systems need a bookshelf to manage titles

### ISSUE THREAD

**Issue by GeorgeKerscher** [daisy/ebraille#29]
As a reader of digital braille, I get titles from a variety of sources. Some of these libraries use the DAISY Online Protocoled, others use the OPDS feeds used in the mainstream, and yet others have an API to review the catalog. Not only are there titles to choose from, but also information about the braille format and if tactile graphics are included as well as math.
Problem statement:  
Libraries and organizations serving persons with disabilities want to support a wide range of formats used by their customers and patrons.  The library lists the titles and the formats available. Some also include titles for embossing. The user of a reading system that has single line or multiple line  refreshable display wants to choose the title that is best suited for their device. The end user will subscribe to a variety of libraries and wants to use the bookshelf feature in the reading system to manage the titles have available to them. To make the right decision, the bookshelf search feature will need to display metadata about the title, e.g., the language, the braille format, the grade of the braille, if tactile graphics are included, if math is supported. The end user may also have an embosser and if an  embosser ready file is available may want to obtain that file; they will need to know if their embosser is supported in that file.

This sophisticated bookshelf function enables the end users to obtain the titles they want, and helps the library serve more people without personal intervention.

**Comment by wfree-aph** [comment]
This feature is more of a requirement for reading systems but the metadata included in the spec and the use of the EPUB packaging format make it possible for reading systems to implement this feature.
