### ISSUE TITLE
Graphics in braille files

### ISSUE THREAD

**Issue by jrbowden** [daisy/ebraille#3]
As a braille producer or braille reader, I want to benefit from inclusion of graphics as well as text in braille documents.

*Detail:*
Assuming I have a device capable of showing tactile graphics as well as braille, I want to make use of graphics as well as just the text in a document.
Currently, a braille document can only store the text component of the document; graphics have to be stored separately.

*Proposal:*
Tactile graphics can be stored alongside text in a braille file, so that those braille displays or embossers capable of displaying tactile graphics can incorporate them into the document.
The format for any such tactile graphics is to be discussed.

**Comment by avneeshsingh** [comment]
This issue was discussed in the meeting held on September 6, 2022.
* Current no braille first file format allows placing graphics and text in the same file.
* On the other hand main stream standards like XHTML, HTML etc and DTBook 2005 standards allow this.
*

**Comment by rjaquiss** [comment]
Should an option be available to include different tactile files such as those for ViewPlus embossers, Index embossers, capsule paper machines?

**Comment by jrbowden** [comment]
I think that depends on what kind of graphic file format is used:
If it is an image at a particular dot resolution, designed specifically for one kind of embosser, then yes you are right.
However, if instead, the image is a high res image that always has to be processed in order to render on any embosser, then no.
I think also someone mentioned formats such as SVG  which will allow scaling to any resolution without loss of clarity.

So perhaps the question is, should images be generic or designed for a particular dot resolution?

**Comment by mhorspool** [comment]
We should settle on a single, platform-agnostic file format for images. Conversion tools can then be created, either by us or by device manufacturers, to ensure compatibility with differing products.

**Comment by mrhunsaker** [comment]
I agree with @mhorspool that we need a single format for images. My concern with using PRN files generated from Tiger Designer or another software is that a lot of trust is placed in the individual generating the file not limit it to a given embosser.

per @jrbowden I think we do absolutely need a certain dot resolution, and we can look at current embosser embossing resolution as well as what resolution would be useful for use with the emerging tactile displays. I have dealt with far too many situations with US Letter size 1200+ dpi image files that end up taking up far too much space

**Comment by mattgarrish** [comment]
The only potential issue I see here is with EPUB's core media type requirements. If we were to use EPUB, tactile graphics could require fallbacks.

**Comment by GeorgeKerscher** [comment]
The more I learn and think about this issue, I envision JPG, PNG needing to be displayed. More importantly, SVG would allow the tactile image to be zoomed in and out. Also, we should assume that touch screens would be used where live regions would be labeled  and when touched audio files could be played or text displayed. To me this is the perfect use of SVG. I think it meets all the requirements. SVG is already a core media type in the formats we are looking at.

I would love to see a map of a country and then drill down to get the map of a region, and then down to the city level. SVG supports all of this.

**Comment by rjaquiss** [comment]
Hello Colleagues:

 

     I would think an SVG file would work for graphics. Zooming into a file to look at smaller regions would be great. This I am sure would require special software that could be tailored to each device. If an SVG file isn’t available, a way should be made to allow the reader access to whatever format is available.

 

Regards,

 

Robert

**Comment by Menelion** [comment]
Agreed with points on SVG. Plus, it's a portable and compressible format which even adds benefits for using it.
