### ISSUE TITLE
Ability for end-users to suppress blank lines

### ISSUE THREAD

**Issue by jennifersutton** [daisy/ebraille#34]
I am noting this issue as requested in a comment by @wfreeman-aph which reads: "At the meeting: potential suppression of blank lines and that a new issue should be made for this use case."

 Reference: 
https://github.com/daisy/ebraille/issues/28#issuecomment-1267134708

Sometimes, screen readers offer the option to suppress blank lines, so this may not be a common scenario.

**Comment by jennifersutton** [comment]
For reference, the possible need for this occurred to me when I saw a post on an email list. This post was circulated on a couple of additional email lists related to braille. I believe the archives are public, so this link to the post should work:

https://groups.io/g/tech-vi/message/2688

Note, in case helpful, that this is an "announce-only" email list.

**Comment by wfree-aph** [comment]
The use of the EPUB packaging format, CSS, and xHTML make this feature possible but it will rely on reading systems and authors taking advantage of the file type. However, since the specification supports it, I am marking this as resolved.
