### ISSUE TITLE
Ability for Reading Systems to Handle EBRF, BRF, and PEF Gracefully

### ISSUE THREAD

**Issue by jennifersutton** [daisy/ebraille#35]
This may relate to #26, but my sense is that this will be more of an issue for reading systems.

Basically, if an end-user opens a BRF or PEF file in a system that has focused on presenting EBRF, the older documents should still work, relatively seamlessly from an end-user's perspective.

Also, reading systems that cannot handle the full functionality of EBRF will need to render that content as a "flat" BRF, or something else, while assuring that the experience isn't too difficult for end-users to handle.

In HTML, we had the concepts of "graceful degradation" or "failing gracefully." This is the idea I am trying to convey.

Authoring tools may be able to support some of this transformation.

**Comment by jrbowden** [comment]
Agree. BRF, BRL, BRA, PEF files will be around for quite a while so, although this new file format gives a lot of flexibility and additional functionality, the older formats should definitely still be handled.
The reading systems should fail gracefully if the user attempts some function that cannot be handled by an older format. E.g. user wants to jump to next heading in a BRF or PEF file: either an error beep or message could be displayed to warn that heading navigation is not supported in BRF files.
Similarly, reflowing of text from BRF files is possible with assumptions (e.g. that ordinary paragraphs are always indented and runover lines are not). Very much assumptions and they don't always work, but this could be a setting on the reading device.

**Comment by wfree-aph** [comment]
This feature request is outside of the scope of the eBraille specification. It would definitely be ideal for reading systems to continue to support the other braille formats but it is outside of our control and entirely dependent on reading systems. Closing this as not implemented.
