### ISSUE TITLE
Specify 6 or 8 dot braille

### ISSUE THREAD

**Issue by jrbowden** [daisy/ebraille#36]
Most literary braille codes employ six dots, but many refreshable braille displays can display eight dot braille codes.
As a producer, I need to specify whether the braille is six- or eight- dot code.
As a production house, I need to know if the braille is six- or eight-dot.

These details should probably be captured in metadata, see #27 and other related issues.
This also affects how the braille will be encoded, see #2. ASCII braille, in all its various types, is primarily intended for six-dot braille. Unicode braille can accommodate either.

**Comment by wfree-aph** [comment]
Same as #131, this issue can be resolved.
