### ISSUE TITLE
Markup should aid the backtranslation of braille

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#43]
As the developer of a reading system that will open eBraille files, I want there to be enough semantic markup within the eBraille file that it is possible to backtranslate the braille within the file.

*Detail:*
Backtranslating braille is an imperfect process. With a limited character set, many braille characters have multiple meanings and the meaning intended can only be understood with context. Sometimes that context is relatively close to the location of the character in question, such as the character that precedes or follows it and sometimes that context is outside of the braille cells themselves and the process of deciphering those characters can be made easier using markup.

Being able to backtranslate the braille should offer many new features to reading systems. One such feature is offering text-to-speech support without an additional print file. The reading system could backtranslate the braille and then generate the text-to-speech from the text generated by the backtranslation process. Another potential feature is making the eBraille file editable. This means that if changes are needed to update the file, a braille transcriber could edit the existing file more easily than starting over with a fresh translation. Finally, being able to backtranslate the file could make the reading experience more dynamic and give the reader more control over how the content is presented to them. An example here is identifying sections of text that are emphasized so that the reader can choose to ignore emphasis entirely.

*Proposal:*
The eBraille file type should include markup that will aid the backtranslation process. Markup that will aid in this process includes identifying text that is: emphasized (bold, italics, etc) or switches from one language, braille code, or braille grade to another. There may be other aspects that need to be considered but I am thinking that this use case is concerned only with inline markup. I can't think of markup that occurs on the block level that will affect backtranslation.

**Comment by skntkacm** [comment]
Wouldn't Liblouis connection help in this matter? If the mark-up would contain a tag for braille-table identification, it might help then a screenreader to interpret and back-translate braille cells in the file with appropriate Liblouis library. Or perhaps I do not understand completely what was ment by back translation.

**Comment by wfree-aph** [comment]
The [Tagging Best Practices](https://github.com/daisy/ebraille/blob/main/best-practices/tagging/index.html) document presents several ways for content authors to mark code changes and emphasis. Both of these options will rely on authors implementing them properly and backtranslation will depend on the reading system but the feature is supported.
