### ISSUE TITLE
Include spine in eBraille package

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#44]
Use case #11 suggests splitting the text into multiple files. Reading systems will require some means to know the default order of these files.

*Detail*
Whether the text of the eBraille file is split by volumes, chapters, or some other division, reading systems will need a way to know the default reading order. Spines are included in ePUB packages and could be a way to manage this need within the eBraille format.

*Proposal*
Include a spine within the eBraille package that reading systems can use to know the default order of braille files included in the package.

**Comment by JaviONCE** [comment]
It would be desirable to mark which text is part of the cover in the original edition of the book (ink cover), flap notes, etc. All these contents have an equivalent in the original ink book.
It is also good to delimit specific content to the braille edition, such as explanatory notes on braille transcription, tables of special braille signs, etc. All these contents have no equivalence in the original book edition

**Comment by wfreeman-aph** [comment]
Thanks @JaviONCE! You've made a really great point here and I am going to make a use case specifically for ink materials. I knew those existed but hadn't thought of how they would need to be included in the eBraille bundle. We should also have a use case for denoting the braille specific content, as you described, so I'll make a use case for that too.

**Comment by wfree-aph** [comment]
Since we are basing eBraille on the EPUB packaging format, which includes a spine, this issue can be marked as resolved.
