### ISSUE TITLE
Tactile Graphics Taskforce Problem Statement Draft

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#46]
The following is a draft of the problem statement for the Tactile Graphics Task Force, please review it and offer any changes in a comment below. I will update the draft based on those comments. This has been reviewed by the co-chairs, Mike Paciello and Danielle Montour, though they may both have further comments and revisions.

# Tactile Graphics Taskforce Problem Statement 

## Context 

Tactile graphics are images that have been adapted for the sense of touch. They can be produced in many ways, including by hand, on an embosser, or using a multiline display that uses pins. When produced on an embosser or multiline display, the graphic is stored as a digital file. Usually, this file is kept separate from the rest of the text and must be produced independently. 

One of the goals of the eBraille project is to have tactile graphics included with braille files. This goal requires that there be both a means within the braille file to retrieve the necessary tactile graphics file and that those files can be stored within the eBraille bundle so they can be retrieved. 

## Issue 

Digital tactile graphics can be generated as SVG, PDF, PRN, JPG, PRN, or other file types. It is necessary that digital tactile graphic file formats proposed for inclusion in the eBraille format conform to the project principle that it remains "mainstream if possible". Therefore, a solution is needed that is possible within the confines of xHTML, which is the basis for the eBraille file format.  

There are many features that could be included in tactile graphics in the future. It would be useful to consider ways that these features could be possible within our proposal even if those features are not included in the eBraille file format. 

## Scale 

Whether the goal is to provide high-quality digital files or produce embossed graphics, including the graphic file with the braille text supports a better experience for all braille users. When producing embossed graphics, having the file referenced from within the same file as the text should allow embossers to seamlessly reproduce both braille and graphics without the need for manual intervention, as occurs now. When producing graphics using a dynamic medium like a multiline display, having the braille and graphics bundled together should support users accessing graphics when needed and without confusion or unnecessary extra steps. 

## Principles 

* Same principles as eBraille project- the focus on this effort is to propose a solution for including tactile graphics within the eBraille file format and should therefore follow the same principles as that project. Those principles are braille encoding first, mainstream if possible, refreshable braille focus, and to consider less sophisticated devices but not be limited by them. 
* Consider new features that could benefit digital tactile graphics- While it may not be possible to include every feature we propose, it will benefit the eBraille file format working group to know which features are considered and to prioritize the inclusion of those worth the effort.

**Comment by clapierre** [comment]
Did we decide on this?

> Therefore, a solution is needed that is possible within the confines of xHTML, which is the basis for the eBraille file format.

**Comment by wfree-aph** [comment]
The Tactile Graphics Taskforce's main task is completed at this time. Closing this issue as resolved.
