### ISSUE TITLE
Production of braille files

### ISSUE THREAD

**Issue by jrbowden** [daisy/ebraille#5]
As a braille production house, creating braille books which can be embossed or read using refreshable braille displays, I want to incorporate any new features provided by a new braille file standard into our normal work process with ease, ideally simply by selecting a different final output file type in our braille production software.

*Detail:*
Any new braille file standard which meets the requirements of the Problem Statement, should ideally be incorporated into existing braille translation and production software, so for example, a braille transcriber can just pick the new format when saving or exporting the file.

*Proposal:*
Braille translation software developers should be encouraged to incorporate any new braille file format standard into their software as a standard import/export option. It should be handled as one of the file formats natively supported by the software.

**Comment by franciscoONCE** [comment]
Connected with my comment regarding the use of Unicode braille characters. Though it seems hard to envisage a unique braille format that is both a "reading format" and a "printing format" (meaning with the page structure that books in braille are produced and embossed today), it would be possible to produce and output suitable for our printing requirements out of a highly-structured fully-navigable braille file. I'm not sure if I'm talking here of a unique e-braille format that can be printed out as a "professionally embossed" braille book, or two different formats, one for reading electronically and one for printing and/or exporting.

**Comment by mrhunsaker** [comment]
This seems a matter of will rather than technology. As such, I support the proposal. Although fulfilling a separate need with regards to braille, the pretextbook project has straight forward methods for converting among web-based (math read via screenreader using SRE with Nemeth as an output) and embossable with only a few lines of Python.
