### ISSUE TITLE
Support for tactile graphic file types that aren't traditional image file types

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#56]
I am a tactile graphic artist and many of the tactile graphics that I prepare are in a format that is not traditionally considered an image file type. Most of my graphics are either PRN or PDF. It would benefit me if my traditional method of working was supported by this new file type.

*Detail*
Many tactile graphics are produced in a file type that is not necessarily supported by many markup languages as an image. This means that there are thousands of tactile graphics already in existence that could need to either be converted to a different file type or no longer be used if they are not supported by the eBraille file type. It would smooth the transition to the eBraille file type if current workflows and file types continued to be supported.

*Proposal*
While markup languages have methods for displaying traditional image file types such as jpg and prn, it not clear if those same methods would work for file types such as PDF or PRN. If either of those files types, or one with similar issues, is supported by eBraille, we may need to devise a method for displaying them that is different than what is traditionally used.

**Comment by ManfredMuchenberger** [comment]
We also store our tactile graphics in PDF format. But we could also export them in other image formats from our drawing software (CorelDrow). 
I see it as imperative that a reading system (which supports graphics at all) must support a defined small selection of image standards. It is not realistic to expect reading systems to support a very large number of image formats. 
So I think we should define in the standard a small number of image standards that must be supported. And a list of other image standards that are also allowed in the standard but only optionally supported.

**Comment by jrbowden** [comment]
Another type of tactile image should be a traditional style "braille graphic" (in whatever form) such that braille cells are simply rendered close-up with no gaps. e.g. using braille characters a simple box would be:

pccl
l  l
ccca

This gives a dot-for-dot braille graphic. Format how this is to be packaged to be determined.

**Comment by andrewflatres1** [comment]
I would stress that the braille spacing can be customised by the user, as I am sure there will be many options.
The problem with PRN files currently is that the spacing is more centralised with the resolution of embosser dots and not refreshable braille.




Thanks
Andrew

**Comment by wfree-aph** [comment]
This issue is a duplicate of issue #172, which also includes a solution. We just need to update the Best Practices document.
