### ISSUE TITLE
Braille without any transcription errors

### ISSUE THREAD

**Issue by ManfredMuchenberger** [daisy/ebraille#6]
As a braille display user, I want to be able to read e-books that show on a braille display as contracted six dot braille without any transcription errors. So basically I want to read the same quality of braille on my braille display that I can get as embossed paper braille from my library.

Detail:
Currently, e-books only contain an ink print version of the text.
Due to very complicated braille contraction rules and exceptions it is not possible for screenreader or braille display manufacturers to convert this text into error-free braille. This is a fact for German contracted braille and maybe also for other languages.

Proposal:
Using a digital text file format that contains a pre-transcribed braille version of the text in Unicode braille characters.

**Comment by franciscoONCE** [comment]
Another excellent reason to incorporate Unicode characters into the new format.

**Comment by ManfredMuchenberger** [comment]
When reading the whole Problem Statement again (which in my opinion is a very good description of the problem) I stumbled across something I think is worth changing.
In the last paragraph of the chapter "Issue" just before the chapter "Scale" begins. 
https://daisy.org/activities/projects/ebraille/problem-statement/ 

It is clear that content and presentation must be separated. But to my opinion at least part of the formatting should be adapted by the reading system according to the device that is being used for reading. So it will not completely be "retained" from the braille file. Also I wouldn't call "braille translation" simple and it can't be completely error-free automated by reading software. At least not for German contracted Braille. This "error free braille translation" will be the most important reason for us to introduce e-braille.
My suggestion is to just delete this paragraph in the Problem Statement, as the file sharing is already sufficiently described in the paragraph above this.

**Comment by avneeshsingh** [comment]
What priority should be assigned to this use case? High, Medium or low?

**Comment by ManfredMuchenberger** [comment]
For us (SBS) Braille without any transcription errors is high priority, because it would be one of the main reasons for a new e-Braille format in german language (contracted german braille).

**Comment by mhorspool** [comment]
Presumably this means settling on a single encoding scheme, e.g. UniCode/Northamerican ASCII etc.

Braille without any transcription errors relies on transcribers a) being involved, and b) not making any mistakes, and I don't think we can stipulate this in the standard!

**Comment by wfreeman-aph** [comment]
Relates to braille-first file specification. Encoding must be consistent. Must all use Unicode or NA ASCII. May want to make that clear in the title and description.

**Comment by franciscoONCE** [comment]
NA ASCII (as any other ASCII-based set of characters, for that matter) is too limited. Unicode is preferrable for a wider internationalization of the project.

**Comment by mattgarrish** [comment]
All the publishing formats support Unicode, so I don't see any of their use as a problem here.

**Comment by ManfredMuchenberger** [comment]
> All the publishing formats support Unicode, so I don't see any of their use as a problem here.

Yes Unicode will most probably be the best choice. I also don't see a problem here as long as we don't rely on generating the contracted Braille from plain text on the fly in the reading app/device.

**Comment by wfree-aph** [comment]
Since the [first draft of the specification](https://github.com/daisy/ebraille/blob/main/index.html) uses Unicode braille, we can close this issue as resolved.
