### ISSUE TITLE
Tags for Paragraphs

### ISSUE THREAD

**Issue by wfreeman-aph** [daisy/ebraille#67]
This should be built in. You have \<p> in HTML for paragraphs.

BANA regions have multiple kinds of paragraphs. Blocked and indented are the main two and then both can be in a state referred to as "displayed" which modifies the margins and blank line rules. Main point here is that each has different margins and different blank line rules, but all could be covered by the \<p> tag and just use different elements to distinguish them for CSS.

There are also other aspects of braille formats that could use the \<p> tag like directions, a generic non-heading piece of centered text, the transcriber's notes style, and captions.

Overall, \<p> could be used to represent non-list and otherwise not "special" aspects of braille formatting and just use different elements to distinguish them from each other. This aspect could be applied internationally, and we'd just need to agree on what aspects are covered and what elements are used to distinguish them for CSS. The elements used would be either attributes, classes, or maybe something else. We just need to agree on that too.

Questions: What paragraph styles are needed internationally? Are there better tags that could be used for elements that aren't exactly paragraphs like transcriber's notes (which in BANA rules are indented in cell 7 with all subsequent lines in cell 5 and have no blank lines inherent within themselves)? Is there danger in "overusing" the \<p> tag?

**Comment by skntkacm** [comment]
I support the idea of using <p> as a non-style defined piece of text. It should not contain any rules about indentation. Just marking the block of text until a hard blank line \n is entered. All the specifications of the parragraph should be defined individually, such as "parragraph 2-indented, 0 margins", "parragraph 5-indented, 2-let margin" ...

Unlike most of browsers, we should not add blank line before and after <p>.

**Comment by jrbowden** [comment]
I agree use the standard p tag and use CSS to control any formatting.
However, we need to think about what kinds of things do we want reading systems to navigate directly to: if all kinds of paragraphs are just marked with p, then it is likely that we can only navigate to "any kind of paragraph".
The transcriber note is an interesting case. Remember that transcriber notes can be:
* inline, that is, part of a paragraph
* * an entire paragraph
* * several paragraphs
I personally think a transcriber note is a span element, not a paragraph element - which hopefully means all of the above three cases can be handled.

**Comment by jrbowden** [comment]
Other tags we might need consider include blockquote, code, pre, samp, particularly pre, which will allow text which cannot be automatically wrapped.

**Comment by wfreeman-aph** [comment]
Agree with both @jrbowden and @skntkacm. Depending on how we want to do it, we could have the p-tag with additional classes or attributes that allow us to get very specific. We probably don't want to embed cell information in the attributes but we can call it a blocked or displayed or blockquote, etc. We can also add more than one attribute so we can get even more specific and CSS can handle those in their own specific way.

**Comment by wfreeman-aph** [comment]
Discussion in meeting:

James mentions the question becomes navigation. Do we need more specific if the user wants to navigate to a block, centered, displayed paragraph? William thinks this should be handled anyway as we will need to display those types and so the reading system could navigate using them.

William proposes that we accept <p> as the tag for generic blocks of text and let classes and other attributes define any other differences within them.
