### ISSUE TITLE
Tags for Lists

### ISSUE THREAD

**Issue by wfreeman-aph** [daisy/ebraille#68]
This should be built in. You have \<ul> for unordered lists and \<ol> for ordered lists and then regardless of whichever one you use, list items are separated by \<li> tags. You can make nested lists by nesting additional \<ul> or \<ol> tags. [Examples of different types of lists can be found at this link](https://www.w3schools.com/tags/tag_li.asp). Lists can have classes or attributes applied.

A lot of BANA Formats are just different variations on lists. There are lists, exercises, poetry, glossaries, exercises, indices, text for plays in both prose and verse, and we would probably also need generic styles that allow the transcriber or writing software to force a particular margin but keep the text as a kind of list. All of these could be managed using the standard HTML list styles. Similar conventions could be applies to international braille formatting rules too.

One big question is whether we need both \<ul> and \<ol>. It seems to me that everything could be covered by \<ul>. Is anything lost by using that method or do we gain anything by using \<ol>? Do we need both? It seems like since the numbering and other identifiers comes from the braille text, you wouldn't benefit from \<ol> and it might actually cause problems, but maybe I just don't know enough.

Questions: Similar to \<p> tag. What are the needs internationally? Are there dangers in trying to use list tags for so many kinds of braille formatting? Again, do we need \<ol> sometimes?

**Comment by mattgarrish** [comment]
HTML also has definition lists (`dl`). These are formatted differently from ordered/unordered lists.

**Comment by wfreeman-aph** [comment]
Mentioned in the meeting: also need tables of contents and footnotes in the list tag category.

**Comment by wfreeman-aph** [comment]
From meeting:

George says that having the different types is a huge benefit. Also going to be transforming content that is already using things like bulleted lists.

William mentions thinking that we did not need to rely on things like that and that these would be handled during the conversion process.

James mentions that the reading system will already be adding braille page numbers, so we should also let them handle this too.

Recommendation is to use li and ul, ol, and dl for lists and variations of lists. We can recommend simple lists but leave the other types open for us too. Dl also use dt and dd for definition terms and descriptions.
