### ISSUE TITLE
Tags for Tables

### ISSUE THREAD

**Issue by wfreeman-aph** [daisy/ebraille#69]
This should be built in. HTML has \<table>, \<td>, \<th>, and \<tr>. \<tr> contains its particular row, \<td> contains its particular cell, and \<th> designates a particular cell to be a heading for its row or column. Everything is then contained inside a \<table> tag. [Here is a link to an example](https://www.w3schools.com/tags/tag_table.asp).

BANA regions have multiple kinds of tables. Ideally every table would use what is called the simple layout, a kind of spatial layout that attempts to mimic the layout of the original table, but there often isn't enough room. Even if you had enough room, such a table may end up being so large that it would be too cumbersome to read.

The other BANA table types are basically variations of lists and are called listed, linear, and stairstep. The main aspect of those to understand is that they could still rely on the same tags that are offered by HTML. You would just need some element like an attribute or class to distinguish them from a spatial table.

Questions: How are tables handled internationally? Is CSS robust enough to allow reading systems to choose whether to reproduce a table spatially or in a listed form? Could a user switch between different tables based on preference? Would it be preferable for the user to set their preferred table type before the file is opened or could they change it while the file is open?

**Comment by skntkacm** [comment]
In Slovakia we are going to follow BANA rules while rebuilding it now, although for now the preferred style was listed tables. 
It should be adjustable though, when an user wants to change the table while reading. If possible, if the style allows us.

**Comment by jrbowden** [comment]
In the UK we have "paragraph form" which is probably analogous to one of the BANA formats; we also have ordinary tabular form.
Note however that some tables may be shown in table form across a two-page spread.
The output format of the table should probably be determined both by recommendations in the source, and also user preference on the reading system.
For example, a wide table might have the recommendation in the source that it is shown in linear or paragraph format. This would be fine when embossed on paper. However, a braille display user could choose to navigate around a virtual page as large as needed to show the table in full tabulated form.
There are some other table-related tags, such as thead, tbody, tfoot, caption, figcaption, figure.

**Comment by wfreeman-aph** [comment]
@jrbowden  Good points about additional tags. Those will also be useful. I doubt that many reading systems will be able to do it at first but I really hope that we could get to a point where the hardware could display based on user preference. So even if the file creator suggested that a particular table be viewed, say, as a list, that the user could override that preference and have the table presented spatially. Or vice versa. From our talk about reflowing EPUBs, it seems like a difficult task to accomplish but I'm hopefully that it will eventually be possible, even if the reading system just faked it by reloading the document in the background with the new preference or something similar.

**Comment by wfreeman-aph** [comment]
From meeting: Need a tag or attribute for the table type. Key question will be how you layout the table in a non-spatial way. There's also thead and tbody for table header and table body section. These can designate the row vs column headings. There's also tfoot that could be useful.

David mentions tables can get complex. Like when you try to put multiple rows where otherwise there is only one row. We'll want to review complicated tables when implementing.

Another issue is abbreviating table headings, so we'll want to account for that. Doug mentions <abbr> tag. To repeat table headers, you can do a sticky header on the table. You also need to think about referencing back to previous headings, so it is clear that you're not having new headings but referencing the same previous headings.

Charles mentions Aria braille label. Can be used to help with abbreviations. John also mentions <abbr>.

Group agrees that we can use the table tags as mentioned in the ticket and incudes thead, tfoot, and tbody.
