### ISSUE TITLE
Tags for Page Numbers

### ISSUE THREAD

**Issue by wfreeman-aph** [daisy/ebraille#70]
As far as I know, HTML has no set method to handle page numbers because they are not typically needed. There are options that could be used here.

The closest thing I found was using #pageFooter in CSS but I won't pretend to fully understand if that solution is worth pursuing or would work in our case.

Another aspect to consider here is that page numbers can either be inline or block. Basically, you can either have the page number occupying one of the corners of the page or interrupting the middle of a braille page. When appearing in the corner, it will appear on the same line as other text (inline) and when appearing in the middle of the page, it should occupy the entire line (block). This behavior may vary throughout the world.

However, I'm thinking that page numbers could be handled using either \<div> or \<span> tags. \<div> and \<span> are both somewhat generic in HTML. \<div> is a block-level element and \<span> is an inline element but its possible to have either treated as the other type, so there is versatility with either option.

Then it should be possible for CSS and the reading system to handle placing the page number in the correct location based on the braille page. It's important to note that in a dynamic reading system, it may be ideal for the print page number to only appear when a new print page is encountered but on an embossed page, the convention in BANA regions is to display both the first appearance of the new print page number and to increment that page number with a letter in front of it to signify the same print page continuing on a new braille page (3, then a3, then b3, etc.). International conventions will likely vary.

I think its possible to find a solution that will work internationally but this will be one of the trickiest options and probably require a lot of attention from our group.

Questions: Is there a benefit to using \<span> vs \<div>? Is there a more appropriate tag we should use instead? Am I putting too much faith into CSS and the ability of reading systems to dynamically handle page numbers for embossed braille? Can the very different needs of embossed and dynamic braille be met with one solution?

**Comment by mattgarrish** [comment]
HTML doesn't have a dedicated tag for page breaks, but the DPUB-ARIA module includes the [`doc-pagebreak` role](https://www.w3.org/TR/dpub-aria-1.0/#doc-pagebreak) for identifying these.

The perennial question we've found with epub is whether the number should be part of the text content of the document or contained in an `aria-label`/`title` attribute. Here I expect it will depend on how the reading system is expected to handle them - whether there are fixed conventions for whether they should be rendered in the electronic version or embossed version.

**Comment by jrbowden** [comment]
I tink there are (at least) three  things we need to consider:
* Braille page numbers - these are the numbers of the actual piece of braille paper. Typically, they are rendered in a corner of the page. All possible positions should be available through some to be agreed CSS (extension?): left, centre, right, inner, outer, off; and in either a header or footer position.

* Print page numbers: these numbers refer to the original print numbering. They typically appear in a corner of the page and, like braille page numbers, all positions should be possible by CSS (extension). A complication with print page numbering is that the same print page may span multiple braille pages - or multiple print pages may span one braille page. Different countries have different schemes how to show these cases, a couple mentioned below.

* Notification of a new print page: This is the New Page Indicator or Print Page Indicator shown in the text of the document. In BANA it takes a whole line, interrupting the paragraph if needed. In the UK, it is also a line interrupting a paragraph, but the indicator is centred. The new page indicator is shown at the point where a print page changed.

A couple of schemes for showing the print pages:
In the UK, it is always the print page that occupies the last line of the page. This means you always have just one number and this number may be repeated on several pages.

In BANA, the print page number is prefixed by letters a, b, c etc for any additional pages containing the same print page.

Other schemes may include showing the first and last print page number on the page with a hyphen between, e.g. 2-3.

Print page numbers are given in the source document.

Braille page numbers will probably need to be generated by the reading system. Typical page numbering schemes including arabic and roman numbers should be supported.
In addition, some countries, including BANA may add a page prefix to indicate the kind of page, e.g. t1, t2, t3, p1, p2, p3 ...

**Comment by wfreeman-aph** [comment]
@jrbowden I too was thinking that braille page numbers would be generated by the reading system. It puts the most burden on the act of embossing, since you'd need to format and label everything and take into account the braille page numbering rules for the region but I do think it would be doable. Would be interested to hear from embosser manufacturers on this idea.

Dynamically though, I think that you don't really need braille page numbers. I read ebooks all the time and have no use for the page number. I tend to think of chapters in terms of "time to read" more than anything else. A student would use print page numbers for navigation and to fulfill specific assignments, so you'd want to be able to view them easily via hotkey or displayed all the time but I do think they are a bit overrated outside of academic use cases like citations and those already mentioned.

Good point about types of braille page numbers in BANA (like t- and p-). Those could use section tags and be a part of this ticket.

**Comment by wfreeman-aph** [comment]
Said in meeting: Split conversation into three parts. New page indicator, page header or footer, and braille pages.

Bert mentions that the tagging would have them treated as one thing. Could tell the reading system via stylesheets how to render them.

Jennifer mentions that the print page number with the braille page identifier (a3, b3, c3, etc.) is most likely only to be needed by embosser.

Charles shares how it is done in page breaks now: \<span id="page23" role="doc-pagebreak" aria-label=" Page 23. ">. This will also prevent interrupting other elements. The exact braille you need to display would go in the aria label. The issue with exact braille is you do up hardcording the braille and we may need to revisit that later.

**Comment by wfreeman-aph** [comment]
Question came up as we're working on the BRF to eBRF converter, is why do we aria-labels just for page numbers? We're not using aria-labels anywhere else.

**Comment by mattgarrish** [comment]
You don't have to use aria-label for the page numbers, only if you don't want them rendered by default. As I mentioned above, I don't know if that's a consideration for braille. You can also encode them with just the role:

`<span id="page23" role="doc-pagebreak">23</span>`

**Comment by wfreeman-aph** [comment]
Thank you @mattgarrish. If I'm remembering correctly, the thinking was that the aria-label would assist with navigation. Otherwise the user will have to input braille numbers to navigate by page and that may not be feasible with every reading system.

**Comment by mattgarrish** [comment]
I don't fully understand yet how they'll be encoded, so that could be an issue. But you could suppress the page numbers using the `hidden` attribute, for example, so that they don't have to be braille encoded. It's also not clear to me if you'll use a mechanism like the EPUB/DAISY page list to provide page navigation, as locating/moving to pages will have to occur across document boundaries, in which case the tag itself may only be a destination (and possibly a means of announcing the current page).

But if the issue is strictly about not having to bring in `aria-label`, it's also acceptable to use the HTML `title` attribute to define the name of the page.

**Comment by wfreeman-aph** [comment]
Thanks. The issue we're running into with our converter is that we don't want to add the complication of backtranslating the page number in order to get the print equivalent. We may just leave that part out. It'll be much easier for software that is creating an eBraille file to know the translation of the page number.

**Comment by jrbowden** [comment]
Forgive me if any of this is wrong: I think the print page number should be in braille, just as the rest of the document is.
This span is for showing the print page indicator in the running text of the braille document. In BANA countries it represents the line of dots 36 (by CSS) followed by the new print page number - which of course is in braille.
Note that users should always have to type in braille to find anything - it's a braille file.

Could the page list be handled by the id in the span?

@matt, I like the example you give with the page number as the content of the span, that's much simpler.

I would code the content of the print page indicator as braille dots, just as the rest of the document content.
Hope I've got this right :)

**Comment by GeorgeKerscher** [comment]
Hello,

 

And when the teacher or other person in the book club says, "Let us turn to
page 56." What is going to happen?

 

Best

George

**Comment by jrbowden** [comment]
The student presses the button to jump to page, types in braille number sign, e, f, and presses enter.
The system then looks for a thing with role doc-pagenum and content matching those dots. Voila.

**Comment by mattgarrish** [comment]
> The system then looks for a thing with role doc-pagenum

This is where a page list comes in, at least if we envision a braille document being split across many files. It gets expensive (and slow) to load every document and query its DOM to find the matching element. With a page list the reading system would only need to locate the corresponding entry in the list and then relocate the user to the associated destination.

**Comment by jrbowden** [comment]
True. And I also thought, we still need to define the list of things that a user can navigate to (see e.g. #1). Jumping to a page is a great addition.
