### ISSUE TITLE
Tags for Line Numbers

### ISSUE THREAD

**Issue by wfreeman-aph** [daisy/ebraille#71]
There's not a standard way to handle line numbers that I am aware of in HTML. It's not a common need for web pages or other material as far as I know.

One solution that I found online is to use CSS to set up \<pre> tags to have line numbers appear in a specific location and to automatically increment. I don't know enough to understand if such a solution would work.

As is, the transcriber will know what the line numbers should be, and we probably wouldn't benefit from the autoincrement anyway since that would be a non-braille solution.

Instead, I would propose that we use a \<span> with an element, so an attribute or class, that identifies it for CSS as a unique kind of braille formatting. \<span> is an inline tag, so you would be able to place it inside other tags as needed.

BANA regions have both line numbers for prose and poetry. Each has different rules, but both appear at the end of the line to which they are concerned, and their presence affects where each line must end (so the line numbers do not appear to be a part of the main text). You'd likely need a \<div> to contain the entire piece of line numbered text to ensure that the layout was maintained throughout. Rules also probably vary greatly throughout the world and so CSS would need to do a lot of the heavy lifting to ensure the numbers appeared in the correct location and the associated text began and ended appropriately to accommodate the presence of line numbers.

I suspect that line numbers will be a tricky problem for us to solve and will require a lot of attention.

Questions: Is there a more appropriate tag than \<span>? Am I putting too much faith in CSS to be able to dynamically place line numbers *and* control the start or end of the lines being numbered? And, of course, how are line numbers handled internationally?

**Comment by skntkacm** [comment]
When deciding for the suitable approach, I think important is to consider possibility of its optional use. It has to be very easy to user or not use it, either as a tag or CSS.

**Comment by jrbowden** [comment]
In the UK, line numbers are shown on the left, with the left margin of the text suitably moved right. So yes, using a div for a section of line numbered text would probably be a good idea.
In the UK, we omit the numeral indicator from line numbers.
Line numbers may refer to braille lines or to original print lines. However, as you say, all this is probably set up by the transcriber.

Allowing show/hide line numbers is an interesting idea. Do we need to add this to the show/hide use cases?

**Comment by wfreeman-aph** [comment]
@jrbowden Good info and yes please feel free to add it to the show/hide use case.

**Comment by wfreeman-aph** [comment]
One aspect of this ticket that just occurred to me is that we will also need a container for the line numbers. This container would help account for the spacing and margin changes that can occur within line numbered sections. This container could be a simple div with a class or attribute that identifies it as being related to line numbers. The div container may not be necessary in the long run, as the presence of line numbers may be enough to meet the requirements of braille rules.

Discussed in meeting, that the line numbered would be placed where the line starts and the reading system will handle placing the line number in the appropriate location using CSS.

Some braille regions also have braille vs print line numbers and the method suggested by James in the previous comment.

So resolving with the idea that we will use a span with an id, a role, and an aria-label.
