### ISSUE TITLE
Including Liblouis

### ISSUE THREAD

**Issue by skntkacm** [daisy/ebraille#76]
So far, the best braille data from many countries is being stored in Liblouis tables. Right now it is difficult to estimate, how well will the reading system or screen reader in the future work with e-braille format, but assuming we have a file in unicode braille patterns, implementation of a tag of particular liblouis table may help reading system or screen reader to match it correctly and perhaps interpret the unicode braille better.

**Comment by jrbowden** [comment]
Can you explain further? An eBraille file should contain tags for the language of the text and the braille table used. So there should be no need to try and interpret the braille.

**Comment by skntkacm** [comment]
I am sorry, I was not sure if the tag for "used braille table" was included somewhere. Nevertheless I just wanted to suggest creation of the tag in a way, which would be compatible with Liblouis table names. In a way, that would be easy for reading systems then to match the e-braille tag of "used braille table" and table itself in liblouis. This way then screen readers could possibly interpret unicode braille patterns in the e-braille file as standard text. Perhaps. But if it is already solved or it does not give too much sense technically, please, close the issue.

**Comment by bertfrees** [comment]
I think it is our job to do all the necessary to make it possible to define the exact braille system in metadata (https://github.com/daisy/ebraille/issues/20). At the same time Liblouis should adopt / become compatible with the standard that we create. We should at all costs avoid including metadata that is specific to Liblouis.
