### ISSUE TITLE
Tags for form fields in interactive documents

### ISSUE THREAD

**Issue by jrbowden** [daisy/ebraille#77]
The standard HTML5 tags can be used for input fields. These are:

- button: creates a button
- datalist: a list of predefined options for an input field
- dialog: defines a window for a form
- fieldset: defines a set of related form fields
- form: defines a form for user input.
- input: defines an input control.
- label: the label for an input control.
- legend: the caption for fieldset.
- optgroup: a set of related options in a selection list.
- option: an option in a selection list.
- select: a selection list in a form.
- textarea: a multiline text input control.

There are various attributes specific for form controls, particularly the <em>type</em> attribute for the <em>input</em> tag, which defines the type of control:
- button
- checkbox
- color
- date
- datetime
- datetime-local
- email
- file
- hidden
- image
- month
- number
- password
- radio
- range
- reset
- search
- submit
- tel
- text
- time
- url
- week

Are all of these types required?

Other attributes include (this is not a complete list):
- accept: file types to accept
- autocomplete
- autofocus: whether the field automatically receives input focus
- checked: for checkboxes and radio controls
- disabled
- list: points to the datalist for options
- max, min: maximum and minum values
- maxlength, minlength: maximum and minimum valid length
- multiple: whether the control can accept multiple values
- pattern: regular expression for acceptable input
- readonly
- required
- size: size in characters of the control
- value: initial value of the control

Global HTML attributes such as class, id, lang and name are also available.

Further discussion is needed about the range of possible form controls and their function.

**Comment by mattgarrish** [comment]
Closing this issue similar to #78 as we're using xhtml documents. Many of these tags are available but won't be needed since we're not adding scripting support for the first version.
