### ISSUE TITLE
Tags for miscellaneous others

### ISSUE THREAD

**Issue by jrbowden** [daisy/ebraille#78]
Various other tags may be needed for other document features. These could include:
- hr: a horizontal line - that is, a text break.

Other possibilities include:
- meter: a meter or gauge
- progress: a progress bar
- time: a date or time
- audio
- video
To be discussed.

**Comment by mattgarrish** [comment]
This seems like it can be closed now that it's clear we're using xhtml documents. Please feel free to reopen if there's a specific issue we need to address, although adding to html is out of scope for us.

**Comment by jrbowden** [comment]
Hi Matt, my only concern is hr. Did we discuss how we encode a horizontal "end marker" line, as in UK format at the end of chatpers, or at end of tables, etc?

**Comment by mattgarrish** [comment]
Hi James, I believe hr still may need discussion, but you appear to have an open issue for it in https://github.com/daisy/ebraille/issues/50

I'm trying to close off these earlier (and duplicate) issues that preceded our settling on xhtml's tag set so we can reduce the open issue list to the ones that still need attention. Are you okay with me re-closing this one?

**Comment by jrbowden** [comment]
Sure, yes, if there's a duplicate, then this one can be closed. Things like audio and video are out of scope. Many thanks.
