### ISSUE TITLE
Unit Formatting Requirements

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#81]
Tactile graphics and fixed text materials will need to have their size defined. This will help hardware know if it even is capable of displaying the material and also preparing the material with the correct amount of space. If you've ever opened a website and had the text change position as images are loaded, it's because the developer didn't define the size of the images so the website could preformat the space required as the image loads. We also need a standard way to define cell position, how large blank lines should be, and to define the space between lines. To answer these layout questions, we need to agree on how to define size and space.

One option is to use em, rem, and/or ch. Here's what Bert said about them: "em, rem and ch are units that are relative to the font size. They are the perfect fit for measuring heights (`em` and `rem`) and widths (`ch`) in our use case, as long as there can only be one font and font size for the whole document, the font is monospaced, and line-height: 1em; letter-spacing: 0 yields the expected spacing between dots." 

Definitions that may be helpful here:
- em — font size of the element, relative to its parent (3em means that 3 times the normal font size) 
- rem — font size of the element, relative to the root html element 
- ch — width of the “0” character (in monospace fonts all characters are of equal width) 

Here's [an article that explains different kinds of CSS units in a fairly simple way](https://medium.com/level-up-web/the-difference-between-css-units-px-pt-rem-em-vh-vw-ch-ex-and-the-rest-b2cfdf069230). 

We could also accommodate other units of measure such as pixels (px) or standard units of measure like cm, mm, or in. We don't have to limit ourselves, but we need to determine what will work best. For example, is there any advantage to using relative units of measure that would vary based on the available page size?

It seems that we could benefit from using multiple units of measure. One method would be to use em and ch for text and then use pixels or standard units of measure for graphics. Are there other methods that would be preferable? It is important that we agree and that we use units in a standard way.

**Comment by bertfrees** [comment]
> as long as there can only be one font and font size for the whole document, the font is monospaced, and line-height: 1em; letter-spacing: 0 yields the expected spacing between dots

I think the consequence of this is that the font and font-size have to be fixed by the reading device. In practice this will almost always be the only thing that makes sense anyway.

Another reason for this restriction is that only if this is the case you can reliably express that you want a style sheet to be applied only when the device can contain e.g. at least 10 lines:

```css
@media (min-height: 10em) {
   ...
}
```
You can only say that a device can hold a certain number of lines if the size of one line is well-defined and can not change.

See also https://drafts.csswg.org/mediaqueries/#units.

**Comment by bertfrees** [comment]
In [CSS requirements](https://daisy.github.io/ebraille/#css-req) we now recommend that eBraille creators use font-relative lengths only.

**Comment by wfree-aph** [comment]
Thanks @bertfrees! Closing as resolved.
