### ISSUE TITLE
Blank Line Formatting Requirements

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#82]
This ticket concerns the adding and removing of blank lines. 

It seems that [margin-top](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-top) and [margin-bottom](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-bottom) can cover the needs here. 

Both will allow for adding blank lines and [margin collapse](https://www.w3schools.com/css/css_margin_collapse.asp) can be used to ensure that you don't get two blank lines because two adjacent elements both required a blank line in the same location. So, for example, you have a heading followed by a list and your braille rules require the heading to be followed by a blank line and a list to be preceded by a blank line, margin collapse can ensure you only get one blank line and not two. 

CSS can also be selectively applied. One of the ways this is done is using classes. With classes, you can, for example, use the li style for lists but treat lists differently based on class. You could have a list with a class of "gets a blank" and a list with a class of "no blank" and then the "gets a blank" class could be preceded by a blank line and the "no blank" list wouldn't. These classes could be applied by the writing system contextually. We'd likely need more elegant names and conventions than what is presented here but these just serve as an example.  

You could also have a class that manages elements that appear at the top or bottom of the page and then apply or remove blank lines based on the local rules of braille. Another point here is that an element could have multiple classes (so could have "gets a blank" and "top of page" for example and then get blank lines based on both classes' requirements). 

Are there blank line requirements that wouldn't be covered by margin-top and margin-bottom? There's also padding-top and padding-bottom. Key difference between padding and margin is that padding is the space between an element's border and content while margin is the space around an element's border, so padding is within the element's border while margin is outside an element's border. Not sure how padding could be preferable to margin.

**Comment by bertfrees** [comment]
This should now be covered in the [eBraille Styling Best Practices, under the section "Spacing"](https://daisy.github.io/ebraille/best-practices/styling/index.html#spacing). If you think there are still things missing or not explained well enough, please feel free to reopen the issue.
