### ISSUE TITLE
Simple Cell Position Formatting Requirements 

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#83]
Most cell positioning will be done to block elements, like different types of paragraphs, headings, and lists. In these cases, we just need the braille to be indented to a specific cell position on both the first line and all subsequent lines of that particular block of text. This requirement can be handled using [text-indent](https://developer.mozilla.org/en-US/docs/Web/CSS/text-indent) and [padding-left](https://developer.mozilla.org/en-US/docs/Web/CSS/padding-left) and, potentially, [padding-right](https://developer.mozilla.org/en-US/docs/Web/CSS/padding-right). 

Text-indent can be defined using a unit we define, so we can tie it to the [braille cell spacing](https://github.com/daisy/ebraille/issues/81). It can also be applied to the first line using positive values or subsequent lines using negative values. For example, you could use 3em to get 3-1 spacing or -3em to get 1-3 spacing (with the first number being the first line’s indent and the second number being all subsequent lines). 

If you need to indent both the first line and subsequent lines, you could do so using padding-left. That would push the entire block and then you could do any further indentation using text-indent. For example, if you needed the text to have, for example, 3-7 spacing, you could use padding-left to push everything to the third cell and then use text-indent to push subsequent lines to the 7th cell. 

Centered text will be in a separate ticket since it has its own complex issues. 

What issues are there with the proposal to handle cell positioning using text-indent and padding-left? When would we need to use padding-right?

**Comment by wfreeman-aph** [comment]
@jrbowden, I think you raise a good point but I'm not sure which way to go. I also don't know if we need to be consistent. It's really just a question of which is easier to work with based on the formatting requirements for each situation. Between blocks will definitely be the more complicated situation as you'll have different formatting requirements competing. Not sure if padding or margins will offer any advantages over the other in those kinds of situations. Consistency may be more important than I'm realizing though. Definitely worth discussing!
