### ISSUE TITLE
Centered Cell Position Formatting Requirements 

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#84]
Sometimes text is centered in braille. It is centered based on the available braille cells on the line that the text occupies. For example, if you have a ten cells of text on a forty-cell line and you need to center that text, the text should start in cell 16. That would put 15 cells on the left of the text and 15 cells on the right of the text. 

One way that this requirement could be handled using CSS, is by using [text-align](https://developer.mozilla.org/en-US/docs/Web/CSS/text-align). One of the values that you can apply to text-align is “center”. The problem with this method is that text-align will center the text but not according to braille cell spacing. I can’t find any information that suggests we can tie it to our font size. I also can’t find any information which tells me what value is used to align the text. Is it pixels? 

This problem may not be as difficult as it seems to me. We may be able to use text-align center and just let the reading system handle it. The reading system knows that it is concerned with braille and so will center accordingly. 

Are there any other issues with text-align? Is there a preferable method for centering text?

**Comment by bertfrees** [comment]
I don't think the problem needs to be that difficult. If the text has an uneven number of characters and there is room for an even number within the containing box, or visa-versa, true centering will indeed result in lines of braille cells that are offset with half a cell w.r.t. regular lines. It seems fine to me to let the reading system handle it by shifting the text half a cell to the right or the left. Unless we want the behavior to be completely predictable and consistent across devices:

- An author might prefer shifting to the left or to the right.
- In theory devices could support true centering while that might be undesired for an author.

**Comment by jrbowden** [comment]
I agree, just define the behaviour when there is an odd number of cells, shift left or shift right. Check what other existing translation software was as a model.
There is also a requirement for right aligned text. Again, I think this can be handled with text-align.

**Comment by bertfrees** [comment]
This should now be covered in the [eBraille Styling Best Practices, under the section "Alignment, positioning and spatial arrangement"](https://daisy.github.io/ebraille/best-practices/styling/index.html#alignment). If you think there are still things missing or not explained well enough, please feel free to reopen the issue.
