### ISSUE TITLE
Tags for footnotes and endnotes

### ISSUE THREAD

**Issue by jrbowden** [daisy/ebraille#85]
The appear to be no specific tags for footnotes or endnotes.
The note reference in the running text could be marked with a span. Adding a specific role could categorise the span as a note reference but there appear to be no specific roles for footnote and endnotes.
The note reference might also be a link (so a span containing a link and have a specific role).
The text of footnotes is basically an item in a list, so the usual list tags apply.
Note that notes may sometimes be given at the end of paragraph, chapter, volume or book in braille.
Questions: Is it desirable to use a specific role to identify notes?
Are there any other specific requirements for notes?

**Comment by mattgarrish** [comment]
> Adding a specific role could categorise the span as a note reference but there appear to be no specific roles for footnote and endnotes.

The DPUB-ARIA module has roles for these: [doc-noteref](https://www.w3.org/TR/dpub-aria-1.1/#doc-noteref), [doc-footnote](https://www.w3.org/TR/dpub-aria-1.1/#doc-footnote), and [doc-endnotes](https://www.w3.org/TR/dpub-aria-1.1/#doc-endnotes).

**Comment by wfreeman-aph** [comment]
Discussed that the doc-noteref is the footnote reference (is the superscripted thing in the book), doc-footnote is the footnote itself (is the actual text of the footnote), and doc-endnotes (is the actual text of the endnotes). There was a docendnotes role that is now deprecated and we are not going to do that. For endnotes, the doc-endnotes role gets applied to the section and for footnotes the doc-footnotes gets applied to each individual footnote. We should follow the 1.1 rules, https://www.w3.org/TR/dpub-aria-1.1/.

Question of how different braille rules will be affected by these decisions (like footnotes being moved to after the section or at the end of the page), but it shouldn't be an issue. Will need to review after MVP with international rule systems.
