### ISSUE TITLE
Method for deciding on CSS selectors to accomplish braille formatting

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#89]
In the meeting on July 18th, we discussed how to best define the different types of formatting that braille has using CSS selectors. One method that was discussed involved a tiered system for braille requirements. Using this method, the ticket creator would:

1. Define a braille formatting need
2. Decide if this formatting need could be identified using just the default HTML tags
3. If not, decide if this formatting need could be identified using the roles described by [dpub-aria](https://www.w3.org/TR/dpub-aria-1.0/#role_definitions)
4. If that is not specific enough or already taken by another formatting need, decide if this formatting need could be identified using [class names](https://www.w3schools.com/html/html_classes.asp) and what those class-names should be.
5. If none of the methods appear to work or there are unknown aspects, flag the issue for further attention from the group.

If we utilize this framework, it should be possible to work asynchronously and agree upon how different aspects of braille formatting should be identified within the HTML so that proper CSS can be applied.

An aspect to begin with could be to work on a list of braille formatting needs. Once we had a suitable list, users could volunteer to take an aspect of the list and explore the requirements in this ticket (default tags, dpub-aria, class names, etc). We then continue to review and create tickets for the formatting needs in the list, add new formatting needs as we consider them, and discuss the tickets that have already been created, until we are satisfied with our progress. We'll likely end up with an incomplete list of formatting requirements in our MVP but we'll review and improve in future specifications.

Please comment with any suggestions or alternatives to this proposed method.

**Comment by egli** [comment]
A good starting point for this would probably be the documentation of existing braille formatters such as [dotify](https://github.com/mtmse/dotify.formatter.impl) and to a lesser extent also the formatting specification in [liblouisutdml](http://liblouis.io/documentation/liblouisutdml.html). 

In particular dotify's [OBFL](https://mtmse.github.io/obfl/obfl-specification.html), the well defined _Open Braille Formatting Language_, which in turn is based on [W3C XSL-FO 1.1 standard](http://www.w3.org/TR/xsl/), is quite thorough.

The formatting and [styling options of liblouisutdml](http://liblouis.io/documentation/liblouisutdml.html#style) could be used as a basic starting point.

**Comment by avneeshsingh** [comment]
I would like to highlight to use MVP requirements as our guide.
There are many formatting requirements for braille, which may overwhelm us. So, lets look through the lens of MVP and reduce the scope a little for version 1.0 of specifications.

**Comment by wfreeman-aph** [comment]
After reading the comments on this ticket and thinking about it some more, I've gone ahead and marked this ticket as low priority, which previously meant that the ticket would not be apart of the MVP. I really like the possibility it represents but it greatly simplifies our efforts to not include this work in the MVP. It might actually be easier too for us to instead just focus on MVP and maybe come back later and reconsider this option in a future revision rather than trying to enforce it from the start.

Additionally, reading systems may be able to handle some of the work required here and it could be a feature that a particular reading system uses to stand apart from competitors, so we may never implement this ticket but readers could still potentially benefit as a clever reading system could accomplish the same goal even without a common language of selectors.

**Comment by mattgarrish** [comment]
Just noting that the class attribute is independent of how CSS uses it to apply styles. CSS built a shorthand syntax off the presence of classes to make applying styles easier, but it's not the only attribute you can use as a selector.

Here's the class attribute's definition from the HTML specification:

>When specified on [HTML elements](https://html.spec.whatwg.org/multipage/infrastructure.html#html-elements), the [class](https://html.spec.whatwg.org/multipage/dom.html#classes) attribute must have a value that is a [set of space-separated tokens](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#set-of-space-separated-tokens) representing the various classes that the element belongs to.
> 
> Note
> Assigning classes to an element affects class matching in selectors in CSS, the [getElementsByClassName()](https://dom.spec.whatwg.org/#dom-document-getelementsbyclassname) method in the DOM, and other such features.
> 
> There are no additional restrictions on the tokens authors can use in the [class](https://html.spec.whatwg.org/multipage/dom.html#classes) attribute, but authors are encouraged to use values that describe the nature of the content, rather than values that describe the desired presentation of the content.

The attribute was intended as a kind of general-purpose semantic attribute, as opposed to ARIA and DPUB-ARIA roles which are meant to influence behaviours in assistive technologies.

Nothing stops us from defining processing behaviours for classes, in other words, or restrictions on where you can use them. The problem with a class-based approach is if there is no consensus on how to define and process the classes (or how to style them), which could be the case if we're accommodating regional variations. Styling profiles can be defined independent of the essential technologies of an ebraille format if that's really all classes are needed for.

As an aside, EPUB tried an alternative approach to classes by minting an "epub:type" attribute to apply semantics to HTML elements, but it didn't work out all that well. It was supposed to provide a bridge between semantic markup that publishers use and the roles assistive technologies use, but really only ended up supporting some publisher's internal production needs (plus pop-up footnotes in some reading systems). It was also meant to avoid having any influence over styling. Adopting EPUB would make that attribute available, but it also locks you into XHTML and comes with an uncertain future.

**Comment by wfree-aph** [comment]
I think this issue is resolved by the use of the EPUB packaging format and the inclusion of the [Tagging Best Practices](https://github.com/daisy/ebraille/blob/main/best-practices/tagging/index.html) and [Styling Best Practices](https://github.com/daisy/ebraille/tree/main/best-practices/styling) documents. If I am incorrect in this understanding, please reopen the ticket and help me understand what more we should do to fully resolve this issue.
