### ISSUE TITLE
Internal navigation via hyperlink

### ISSUE THREAD

**Issue by wfree-aph** [daisy/ebraille#9]
As a dynamic braille display user, I want to activate links to navigate to another location within the same document.

*Detail:*
Links are a common way of traversing the web and print documents like EPUB. A common use case for links in a print document is for footnotes and endnotes. The user can activate the link and then be transferred to the location within the document that contains the text of the footnote and then activate a second link to then be transferred back to where they were and continue reading.

Another aspect of links is that they can be embedded in the text that relates to them. An example of this would be when link text is used instead of a URL on the web or when the number of a footnote represents the link to the text of the footnote.

Currently there is no means to have any kind of link within a braille document.

*Proposal:*
Links should be able to be added to the electronic braille file format. They could be modeled after links that exist on the web and in print files like EPUB so that they can be embedded within text, like link text that replaces URLs on the web or when the numbers of a footnote are the link to the footnote in an EPUB.

**Comment by jrbowden** [comment]
I absolutely agree having links would be good. Links could be used for:
- footnotes and endnotes
- tables of contents and indexes
- glossary and defined terms
- See Also sections
 - etc
 - 
However, I disagree that a second link should be included to return to the previous point of reading: this should be a general command as part of the rendering application - it is analogous to the Back button provided on most web browsers. A command should be used to do this and the detail left to the renderer.

Note this is similar to a bookmark function, which should also be a rendering application function.

We could also consider defined named links, so a user could immediately jump to the table of contents, index, notes, title page, start of text, etc, even if there are no actual links to these in the document.

**Comment by avneeshsingh** [comment]
Having links in braille fils is good. If a braille file supports links, then one can use it to go to destination and provide anothr link at destination to come back to original position. So, we can simply say that we need to have links in braille document.
Regarding providing a back button like a web browser, it looks like an implementation detail instead of content requirement.

I think this use case should be high priority?

**Comment by GeorgeKerscher** [comment]
The reading system of course should follow links, and it also should provide the functionality to go back. This is a different reading system requirement. I will create an issue for this reading system functionality.

**Comment by BasileAVH** [comment]
Even if we're able to export the navigability elements of and EPUB or a DAISY file, we might need to consider something different about the table of contents. It's the only part that is accessible anytime by the reader and it should also be something mandatory for the structure of the new format. (linked to #1 and #10)

**Comment by mattgarrish** [comment]
All the publishing formats provide linking mechanisms.

Those that support ARIA would also enable the use of the DPUB ARIA link roles (for identifying links to notes, glossary entries, etc.).

**Comment by bertfrees** [comment]
Also note that PEF could possibly be extended with an internal hyperlink feature.
